Repository eclipse-zenoh/zenoh, pull requests merged in 2024-03, with the labels that each got.

#802 Fix liveliness bug
  zenoh/src/net/routing/hat/client/pubsub.rs
  zenoh/src/net/routing/hat/p2p_peer/pubsub.rs
  zenoh/src/net/routing/hat/router/pubsub.rs
Labels: bug

#813 Simplify Error message
  commons/zenoh-codec/src/zenoh/err.rs
  commons/zenoh-protocol/src/zenoh/err.rs
  io/zenoh-transport/src/shm.rs
  zenoh/src/net/routing/dispatcher/queries.rs
  zenoh/src/queryable.rs
  zenoh/src/session.rs
Labels: enhancement, breaking-change

#829 Add express support
  examples/examples/z_ping.rs
  examples/examples/z_pong.rs
  examples/examples/z_pub_thr.rs
  zenoh/src/publication.rs
  zenoh/src/sample.rs
Labels: new feature

#816 Rename IntoCallbackReceiver trait to IntoHandler trait
  zenoh-ext/src/querying_subscriber.rs
  zenoh/src/handlers.rs
  zenoh/src/liveliness.rs
  zenoh/src/prelude.rs
  zenoh/src/publication.rs
  zenoh/src/query.rs
  zenoh/src/queryable.rs
  zenoh/src/scouting.rs
  zenoh/src/subscriber.rs
Labels: enhancement, breaking-change

#839 Remove unsupported Put/Del in Request/Response
  commons/zenoh-codec/src/zenoh/mod.rs
  commons/zenoh-protocol/src/zenoh/mod.rs
  io/zenoh-transport/src/shm.rs
  zenoh/src/net/routing/dispatcher/face.rs
  zenoh/src/net/routing/dispatcher/queries.rs
  zenoh/src/net/runtime/adminspace.rs
  zenoh/src/session.rs
Labels: release

#821 Remove pull API and protocol support
  Cargo.lock
  commons/zenoh-codec/src/zenoh/mod.rs
  commons/zenoh-codec/src/zenoh/pull.rs
  commons/zenoh-codec/tests/codec.rs
  commons/zenoh-collections/src/ring_buffer.rs
  commons/zenoh-protocol/src/network/declare.rs
  commons/zenoh-protocol/src/zenoh/mod.rs
  commons/zenoh-protocol/src/zenoh/pull.rs
  examples/Cargo.toml
  examples/examples/z_pull.rs
  io/zenoh-transport/src/shm.rs
  zenoh-ext/src/subscriber_ext.rs
  zenoh/src/liveliness.rs
  zenoh/src/net/routing/dispatcher/face.rs
  zenoh/src/net/routing/dispatcher/pubsub.rs
  zenoh/src/net/routing/dispatcher/queries.rs
  zenoh/src/net/routing/dispatcher/resource.rs
  zenoh/src/net/routing/dispatcher/tables.rs
  zenoh/src/net/routing/hat/client/mod.rs
  zenoh/src/net/routing/hat/client/pubsub.rs
  zenoh/src/net/routing/hat/client/queries.rs
  zenoh/src/net/routing/hat/linkstate_peer/mod.rs
  zenoh/src/net/routing/hat/linkstate_peer/pubsub.rs
  zenoh/src/net/routing/hat/linkstate_peer/queries.rs
  zenoh/src/net/routing/hat/p2p_peer/mod.rs
  zenoh/src/net/routing/hat/p2p_peer/pubsub.rs
  zenoh/src/net/routing/hat/p2p_peer/queries.rs
  zenoh/src/net/routing/hat/router/mod.rs
  zenoh/src/net/routing/hat/router/pubsub.rs
  zenoh/src/net/routing/hat/router/queries.rs
  zenoh/src/net/runtime/adminspace.rs
  zenoh/src/net/tests/tables.rs
  zenoh/src/session.rs
  zenoh/src/subscriber.rs
Labels: enhancement, breaking-change

#770 Add connection retry
  Cargo.lock
  DEFAULT_CONFIG.json5
  commons/zenoh-config/Cargo.toml
  commons/zenoh-config/src/connection_retry.rs
  commons/zenoh-config/src/defaults.rs
  commons/zenoh-config/src/lib.rs
  commons/zenoh-config/src/mode_dependent.rs
  commons/zenoh-core/src/macros.rs
  zenoh/src/net/runtime/orchestrator.rs
  zenoh/tests/connection_retry.rs
Labels: enhancement

#862 Remove unmantained complete_n feature
  commons/zenoh-codec/Cargo.toml
  commons/zenoh-codec/src/network/declare.rs
  commons/zenoh-codec/src/network/request.rs
  commons/zenoh-protocol/Cargo.toml
  commons/zenoh-protocol/src/network/declare.rs
  commons/zenoh-protocol/src/network/request.rs
  zenoh/Cargo.toml
  zenoh/src/lib.rs
  zenoh/src/net/routing/dispatcher/queries.rs
  zenoh/src/net/routing/dispatcher/resource.rs
  zenoh/src/net/routing/hat/client/mod.rs
  zenoh/src/net/routing/hat/client/queries.rs
  zenoh/src/net/routing/hat/linkstate_peer/mod.rs
  zenoh/src/net/routing/hat/linkstate_peer/queries.rs
  zenoh/src/net/routing/hat/mod.rs
  zenoh/src/net/routing/hat/p2p_peer/mod.rs
  zenoh/src/net/routing/hat/p2p_peer/queries.rs
  zenoh/src/net/routing/hat/router/mod.rs
  zenoh/src/net/routing/hat/router/queries.rs
  zenoh/src/net/runtime/adminspace.rs
  zenoh/src/session.rs
  zenohd/src/main.rs
Labels: breaking-change

#866 Payload API
  commons/zenoh-macros/build.rs
  plugins/zenoh-plugin-example/src/lib.rs
  plugins/zenoh-plugin-rest/src/lib.rs
  plugins/zenoh-plugin-storage-manager/src/replica/storage.rs
  zenoh-ext/src/group.rs
  zenoh/src/payload.rs
  zenoh/tests/attachments.rs
Labels: enhancement
