Repository eclipse-zenoh/zenoh, pull requests merged in 2024-12, with the labels that each got.

#1591 add Querier
  examples/Cargo.toml
  examples/README.md
  examples/examples/z_pub.rs
  examples/examples/z_querier.rs
  zenoh/src/api/admin.rs
  zenoh/src/api/builders/matching_listener.rs
  zenoh/src/api/builders/mod.rs
  zenoh/src/api/builders/publisher.rs
  zenoh/src/api/builders/querier.rs
  zenoh/src/api/builders/queryable.rs
  zenoh/src/api/key_expr.rs
  zenoh/src/api/matching.rs
  zenoh/src/api/mod.rs
  zenoh/src/api/publisher.rs
  zenoh/src/api/querier.rs
  zenoh/src/api/session.rs
  zenoh/src/lib.rs
  zenoh/src/net/routing/dispatcher/queries.rs
  zenoh/src/net/routing/hat/client/pubsub.rs
  zenoh/src/net/routing/hat/client/queries.rs
  zenoh/src/net/routing/hat/linkstate_peer/queries.rs
  zenoh/src/net/routing/hat/mod.rs
  zenoh/src/net/routing/hat/p2p_peer/pubsub.rs
  zenoh/src/net/routing/hat/p2p_peer/queries.rs
  zenoh/src/net/routing/hat/router/queries.rs
  zenoh/tests/matching.rs
  zenoh/tests/session.rs
Labels: new feature

#1623 Change default config listen endpoints when transport_tcp feature is disabled
  commons/zenoh-config/Cargo.toml
  commons/zenoh-config/src/defaults.rs
  io/zenoh-link/Cargo.toml
  io/zenoh-transport/Cargo.toml
  zenoh/Cargo.toml
  zenoh/src/net/runtime/orchestrator.rs
Labels: enhancement

#1627 Improve congestion control
  io/zenoh-transport/src/common/pipeline.rs
  io/zenoh-transport/src/multicast/link.rs
Labels: enhancement

#1613 Add QoS configuration overwrites for publication messages
  Cargo.lock
  DEFAULT_CONFIG.json5
  commons/zenoh-config/Cargo.toml
  commons/zenoh-config/src/lib.rs
  commons/zenoh-config/src/qos.rs
  zenoh/Cargo.toml
  zenoh/src/api/builders/publisher.rs
  zenoh/src/api/publisher.rs
  zenoh/src/api/sample.rs
  zenoh/src/api/session.rs
  zenoh/tests/qos.rs
Labels: new feature

#1597 feat: add start/stop extension markers for fragment chain
  commons/zenoh-codec/src/transport/fragment.rs
  commons/zenoh-codec/src/transport/init.rs
  commons/zenoh-codec/src/transport/join.rs
  commons/zenoh-codec/src/transport/mod.rs
  commons/zenoh-protocol/src/transport/fragment.rs
  commons/zenoh-protocol/src/transport/init.rs
  commons/zenoh-protocol/src/transport/join.rs
  commons/zenoh-protocol/src/transport/mod.rs
  io/zenoh-transport/src/common/batch.rs
  io/zenoh-transport/src/common/pipeline.rs
  io/zenoh-transport/src/multicast/link.rs
  io/zenoh-transport/src/multicast/rx.rs
  io/zenoh-transport/src/multicast/transport.rs
  io/zenoh-transport/src/unicast/establishment/accept.rs
  io/zenoh-transport/src/unicast/establishment/cookie.rs
  io/zenoh-transport/src/unicast/establishment/ext/mod.rs
  io/zenoh-transport/src/unicast/establishment/ext/patch.rs
  io/zenoh-transport/src/unicast/establishment/open.rs
  io/zenoh-transport/src/unicast/mod.rs
  io/zenoh-transport/src/unicast/universal/rx.rs
  io/zenoh-transport/tests/unicast_fragmentation.rs
Labels: enhancement

#1629 Add TCP buffer sizes configuration
  Cargo.lock
  DEFAULT_CONFIG.json5
  commons/zenoh-config/src/lib.rs
  io/zenoh-link-commons/src/lib.rs
  io/zenoh-link-commons/src/tcp.rs
  io/zenoh-link/src/lib.rs
  io/zenoh-links/zenoh-link-tcp/Cargo.toml
  io/zenoh-links/zenoh-link-tcp/src/lib.rs
  io/zenoh-links/zenoh-link-tcp/src/unicast.rs
  io/zenoh-links/zenoh-link-tcp/src/utils.rs
  io/zenoh-links/zenoh-link-tls/src/unicast.rs
  io/zenoh-links/zenoh-link-tls/src/utils.rs
  zenoh/tests/tcp_buffers.rs
Labels: new feature

#1593 chore: enable rest plugin only if in config or if --rest-http-port is set
  README.md
  zenohd/src/main.rs
Labels: breaking-change, internal

#1636 CI: Fix overlap of keyexpr between qos tests
  zenoh/tests/qos.rs
Labels: internal

#1642 DEFAULT_CONFIG.json5: add missing default config for autoconnect.client
  DEFAULT_CONFIG.json5
Labels: documentation

#1635 Prioritize endpoint config over configuration file
  io/zenoh-links/zenoh-link-tls/src/utils.rs
  io/zenoh-transport/src/multicast/manager.rs
  io/zenoh-transport/src/unicast/manager.rs
  zenoh/tests/tcp_buffers.rs
Labels: bug

#1647 fix: fix callback API
  zenoh-ext/src/advanced_subscriber.rs
Labels: internal

#1648 Update TCP buffer size config
  DEFAULT_CONFIG.json5
  commons/zenoh-config/src/lib.rs
  io/zenoh-link-commons/src/lib.rs
  io/zenoh-links/zenoh-link-tcp/src/utils.rs
  io/zenoh-links/zenoh-link-tls/src/utils.rs
  zenoh/tests/tcp_buffers.rs
Labels: enhancement

#1649 Fix deadlock in subscriber undeclaration
  zenoh/src/api/session.rs
  zenoh/tests/session.rs
Labels: bug

#1582 Add Advanced Pub/Sub feature
  Cargo.lock
  Cargo.toml
  commons/zenoh-config/src/wrappers.rs
  commons/zenoh-macros/src/lib.rs
  zenoh-ext/Cargo.toml
  zenoh-ext/examples/Cargo.toml
  zenoh-ext/examples/examples/README.md
  zenoh-ext/examples/examples/z_advanced_pub.rs
  zenoh-ext/examples/examples/z_advanced_sub.rs
  zenoh-ext/examples/examples/z_query_sub.rs
  zenoh-ext/src/advanced_cache.rs
  zenoh-ext/src/advanced_publisher.rs
  zenoh-ext/src/advanced_subscriber.rs
  zenoh-ext/src/lib.rs
  zenoh-ext/src/publication_cache.rs
  zenoh-ext/src/publisher_ext.rs
  zenoh-ext/src/querying_subscriber.rs
  zenoh-ext/src/session_ext.rs
  zenoh-ext/src/subscriber_ext.rs
  zenoh-ext/tests/advanced.rs
  zenoh-ext/tests/liveliness.rs
  zenoh/Cargo.toml
  zenoh/src/api/admin.rs
  zenoh/src/api/builders/publisher.rs
  zenoh/src/api/builders/sample.rs
  zenoh/src/api/publisher.rs
  zenoh/src/api/session.rs
  zenoh/src/api/subscriber.rs
  zenoh/src/lib.rs
Labels: new feature

#1624 fix(serial-reopening): bug that prevented the serial link to be reused after closing a session
  Cargo.lock
  Cargo.toml
  io/zenoh-links/zenoh-link-serial/src/lib.rs
  io/zenoh-links/zenoh-link-serial/src/unicast.rs
  zenoh/Cargo.toml
Labels: bug

#1644 fix: add unused warning to `CloseBuilder`
  zenoh/src/api/builders/close.rs
Labels: bug, api fix

#1659 Fix zenoh-ext Cargo.toml
  zenoh-ext/Cargo.toml
Labels: internal

#1646 stabilize liveliness API
  .github/workflows/ci.yml
  examples/Cargo.toml
  zenoh-ext/examples/Cargo.toml
  zenoh/Cargo.toml
  zenoh/src/api/liveliness.rs
  zenoh/src/api/mod.rs
  zenoh/src/api/query.rs
  zenoh/src/api/session.rs
  zenoh/src/lib.rs
  zenoh/src/net/runtime/adminspace.rs
  zenoh/tests/liveliness.rs
  zenoh/tests/matching.rs
  zenoh/tests/routing.rs
  zenoh/tests/shm.rs
  zenohd/Cargo.toml
Labels: new feature

#1652 Add interface binding to QUIC link
  Cargo.lock
  io/zenoh-links/zenoh-link-quic/Cargo.toml
  io/zenoh-links/zenoh-link-quic/src/unicast.rs
  io/zenoh-links/zenoh-link-quic/src/utils.rs
  io/zenoh-transport/tests/unicast_openclose.rs
Labels: new feature

#1658 fix: don't emit an error log if pipeline is closed
  io/zenoh-transport/src/common/pipeline.rs
  io/zenoh-transport/src/multicast/mod.rs
  io/zenoh-transport/src/multicast/tx.rs
  io/zenoh-transport/src/unicast/universal/transport.rs
  io/zenoh-transport/src/unicast/universal/tx.rs
Labels: bug, internal

#1660 restored internal_config feature as part of "unstable"
  zenoh/Cargo.toml
Labels: internal

#1663 Add default open timeout for new link establishment
  DEFAULT_CONFIG.json5
  commons/zenoh-config/src/defaults.rs
  commons/zenoh-config/src/lib.rs
  io/zenoh-transport/src/unicast/manager.rs
  zenoh/src/net/runtime/orchestrator.rs
Labels: bug, enhancement

#1662 Add CI for checking markdown format.
  .github/workflows/ci.yml
  .markdownlint.yaml
  commons/zenoh-buffers/README.md
  commons/zenoh-codec/README.md
  commons/zenoh-collections/README.md
  commons/zenoh-config/README.md
  commons/zenoh-core/README.md
  commons/zenoh-crypto/README.md
  commons/zenoh-keyexpr/README.md
  commons/zenoh-macros/README.md
  commons/zenoh-protocol/README.md
  commons/zenoh-result/README.md
  commons/zenoh-runtime/README.md
  commons/zenoh-shm/README.md
  commons/zenoh-sync/README.md
  commons/zenoh-task/README.md
  commons/zenoh-util/README.md
  io/zenoh-link-commons/README.md
  io/zenoh-link/README.md
  io/zenoh-links/README.md
  io/zenoh-links/zenoh-link-quic/README.md
  io/zenoh-links/zenoh-link-serial/README.md
  io/zenoh-links/zenoh-link-tcp/README.md
  io/zenoh-links/zenoh-link-tls/README.md
  io/zenoh-links/zenoh-link-udp/README.md
  io/zenoh-links/zenoh-link-unixpipe/README.md
  io/zenoh-links/zenoh-link-unixsock_stream/README.md
  io/zenoh-links/zenoh-link-vsock/README.md
  io/zenoh-links/zenoh-link-ws/README.md
  io/zenoh-transport/README.md
  plugins/zenoh-backend-traits/README.md
  plugins/zenoh-plugin-example/README.md
  plugins/zenoh-plugin-rest/README.md
  plugins/zenoh-plugin-storage-manager/README.md
  plugins/zenoh-plugin-trait/README.md
  zenoh-ext/README.md
  zenoh-ext/examples/examples/README.md
Labels: internal

#1664 Fix stats bugs
  io/zenoh-transport/src/common/batch.rs
  zenoh/src/net/routing/dispatcher/pubsub.rs
Labels: bug

#1677 fix: exclude internal from automatic changelog
  .github/release.yml
Labels: internal

#1675 Switch to another markdown lint CI check
  .github/workflows/ci.yml
Labels: internal

#1672 Shm mutation example
  examples/examples/z_sub_shm.rs
  zenoh/src/api/query.rs
Labels: enhancement, release, api fix

#1671 Use keyexpr lifetime as lifetime of AdvancedPublisher
  zenoh-ext/src/advanced_publisher.rs
Labels: bug

#1679 reuse zenoh-examples common arguments parsing in zenoh-ext examples
  Cargo.lock
  Cargo.toml
  zenoh-ext/examples/Cargo.toml
  zenoh-ext/examples/src/lib.rs
Labels: internal
