Repository eclipse-zenoh/zenoh, pull requests merged in 2024-06, with the labels that each got.

#1060 fix(1059): adding explicit plugin id in PluginStatus and PluginManager
  commons/zenoh-config/src/lib.rs
  plugins/zenoh-plugin-rest/src/config.rs
  plugins/zenoh-plugin-storage-manager/src/lib.rs
  plugins/zenoh-plugin-trait/src/manager.rs
  plugins/zenoh-plugin-trait/src/manager/dynamic_plugin.rs
  plugins/zenoh-plugin-trait/src/manager/static_plugin.rs
  plugins/zenoh-plugin-trait/src/plugin.rs
  zenoh/src/net/runtime/adminspace.rs
  zenoh/src/plugins/loader.rs
Labels: bug, breaking-change

#1071 fix: Decrease `zenoh_link_udp::UDP_MAX_MTU` to fit UDP over IPv6
  io/zenoh-links/zenoh-link-udp/src/lib.rs
Labels: bug

#1079 fix: missed renames from name to id in plugins
  plugins/zenoh-plugin-trait/src/manager.rs
  plugins/zenoh-plugin-trait/src/manager/static_plugin.rs
  zenoh/src/net/runtime/adminspace.rs
  zenoh/src/plugins/loader.rs
Labels: bug

#1090 fix: Improve debug messages in `zenoh-transport`
  io/zenoh-transport/src/multicast/link.rs
  io/zenoh-transport/src/unicast/manager.rs
  io/zenoh-transport/src/unicast/universal/link.rs
Labels: enhancement

#1105 Enable `zenoh/internal` feature in `zenohd` crate
  zenohd/Cargo.toml
Labels: bug, dependencies

#1123 Fix interface name scanning when listening on IP unspecified for TCP/TLS/QUIC/WS
  io/zenoh-links/zenoh-link-quic/src/unicast.rs
  io/zenoh-links/zenoh-link-tcp/src/unicast.rs
  io/zenoh-links/zenoh-link-tls/src/unicast.rs
  io/zenoh-links/zenoh-link-udp/src/unicast.rs
  io/zenoh-links/zenoh-link-ws/src/unicast.rs
Labels: bug

#1136 Enable releasing from any branch
  .github/workflows/release.yml
Labels: new feature, internal

#1138 replier_id() returns Option<ZenohId>
  zenoh/src/api/query.rs
  zenoh/src/api/session.rs
Labels: bug

#1142 feat: add `Selector::into_owned`
  zenoh/src/api/queryable.rs
  zenoh/src/api/selector.rs
Labels: new feature

#1130 Fix interest protocol when client connected to peer
  zenoh/src/net/routing/dispatcher/face.rs
  zenoh/src/net/routing/dispatcher/interests.rs
  zenoh/src/net/routing/dispatcher/mod.rs
  zenoh/src/net/routing/dispatcher/pubsub.rs
  zenoh/src/net/routing/dispatcher/queries.rs
  zenoh/src/net/routing/dispatcher/tables.rs
  zenoh/src/net/routing/hat/client/interests.rs
  zenoh/src/net/routing/hat/client/mod.rs
  zenoh/src/net/routing/hat/client/pubsub.rs
  zenoh/src/net/routing/hat/client/queries.rs
  zenoh/src/net/routing/hat/linkstate_peer/interests.rs
  zenoh/src/net/routing/hat/linkstate_peer/mod.rs
  zenoh/src/net/routing/hat/linkstate_peer/pubsub.rs
  zenoh/src/net/routing/hat/linkstate_peer/queries.rs
  zenoh/src/net/routing/hat/mod.rs
  zenoh/src/net/routing/hat/p2p_peer/interests.rs
  zenoh/src/net/routing/hat/p2p_peer/mod.rs
  zenoh/src/net/routing/hat/p2p_peer/pubsub.rs
  zenoh/src/net/routing/hat/p2p_peer/queries.rs
  zenoh/src/net/routing/hat/router/interests.rs
  zenoh/src/net/routing/hat/router/mod.rs
  zenoh/src/net/routing/hat/router/pubsub.rs
  zenoh/src/net/routing/hat/router/queries.rs
Labels: bug

#1158 Implement serialize/deserialze for Value
  zenoh/src/api/bytes.rs
  zenoh/src/api/session.rs
  zenoh/src/api/value.rs
Labels: new feature

#865 Refactor Liveliness implementation
  zenoh-ext/Cargo.toml
  zenoh-ext/tests/liveliness.rs
  zenoh/src/api/admin.rs
  zenoh/src/api/liveliness.rs
  zenoh/src/api/publisher.rs
  zenoh/src/api/query.rs
  zenoh/src/api/session.rs
  zenoh/src/api/subscriber.rs
  zenoh/src/net/routing/dispatcher/face.rs
  zenoh/src/net/routing/dispatcher/interests.rs
  zenoh/src/net/routing/dispatcher/mod.rs
  zenoh/src/net/routing/dispatcher/queries.rs
  zenoh/src/net/routing/dispatcher/resource.rs
  zenoh/src/net/routing/dispatcher/token.rs
  zenoh/src/net/routing/hat/client/interests.rs
  zenoh/src/net/routing/hat/client/mod.rs
  zenoh/src/net/routing/hat/client/pubsub.rs
  zenoh/src/net/routing/hat/client/queries.rs
  zenoh/src/net/routing/hat/client/token.rs
  zenoh/src/net/routing/hat/linkstate_peer/interests.rs
  zenoh/src/net/routing/hat/linkstate_peer/mod.rs
  zenoh/src/net/routing/hat/linkstate_peer/pubsub.rs
  zenoh/src/net/routing/hat/linkstate_peer/queries.rs
  zenoh/src/net/routing/hat/linkstate_peer/token.rs
  zenoh/src/net/routing/hat/mod.rs
  zenoh/src/net/routing/hat/p2p_peer/interests.rs
  zenoh/src/net/routing/hat/p2p_peer/mod.rs
  zenoh/src/net/routing/hat/p2p_peer/pubsub.rs
  zenoh/src/net/routing/hat/p2p_peer/queries.rs
  zenoh/src/net/routing/hat/p2p_peer/token.rs
  zenoh/src/net/routing/hat/router/interests.rs
  zenoh/src/net/routing/hat/router/mod.rs
  zenoh/src/net/routing/hat/router/pubsub.rs
  zenoh/src/net/routing/hat/router/queries.rs
  zenoh/src/net/routing/hat/router/token.rs
  zenoh/src/net/routing/mod.rs
  zenoh/src/net/routing/router.rs
  zenoh/tests/liveliness.rs
Labels: enhancement, internal

#1073 Add certificate and user/password authentication methods to ACL filters
  Cargo.lock
  Cargo.toml
  DEFAULT_CONFIG.json5
  commons/zenoh-config/src/lib.rs
  io/zenoh-link-commons/src/lib.rs
  io/zenoh-link-commons/src/unicast.rs
  io/zenoh-links/zenoh-link-quic/Cargo.toml
  io/zenoh-links/zenoh-link-quic/src/unicast.rs
  io/zenoh-links/zenoh-link-serial/src/unicast.rs
  io/zenoh-links/zenoh-link-tcp/src/unicast.rs
  io/zenoh-links/zenoh-link-tls/Cargo.toml
  io/zenoh-links/zenoh-link-tls/src/unicast.rs
  io/zenoh-links/zenoh-link-udp/src/unicast.rs
  io/zenoh-links/zenoh-link-unixpipe/src/unix/unicast.rs
  io/zenoh-links/zenoh-link-unixsock_stream/src/unicast.rs
  io/zenoh-links/zenoh-link-vsock/src/unicast.rs
  io/zenoh-links/zenoh-link-ws/src/unicast.rs
  io/zenoh-transport/src/unicast/authentication.rs
  io/zenoh-transport/src/unicast/establishment/accept.rs
  io/zenoh-transport/src/unicast/establishment/ext/auth/mod.rs
  io/zenoh-transport/src/unicast/establishment/ext/auth/usrpwd.rs
  io/zenoh-transport/src/unicast/establishment/open.rs
  io/zenoh-transport/src/unicast/lowlatency/transport.rs
  io/zenoh-transport/src/unicast/mod.rs
  io/zenoh-transport/src/unicast/transport_unicast_inner.rs
  io/zenoh-transport/src/unicast/universal/transport.rs
  zenoh/Cargo.toml
  zenoh/src/net/routing/interceptor/access_control.rs
  zenoh/src/net/routing/interceptor/authorization.rs
  zenoh/tests/acl.rs
  zenoh/tests/authentication.rs
Labels: new feature

#1177 Remove `zenoh-shm` dev dependency on `zenoh-shm test`
  .github/workflows/ci.yml
  Cargo.lock
  commons/zenoh-shm/Cargo.toml
Labels: bug

#1182 fix: adminspace encodings
  plugins/zenoh-plugin-rest/src/lib.rs
  zenoh/src/net/runtime/adminspace.rs
Labels: bug

#1194 Fix #1185. Add encoding option to publisher creation
  examples/examples/z_pub.rs
  zenoh/src/api/builders/publisher.rs
  zenoh/src/api/publisher.rs
  zenoh/src/api/session.rs
  zenoh/tests/qos.rs
Labels: enhancement

#1184 fix: replace some unsafe code with safe version
  commons/zenoh-buffers/src/bbuf.rs
  commons/zenoh-buffers/src/lib.rs
  commons/zenoh-buffers/src/slice.rs
  commons/zenoh-buffers/src/vec.rs
  commons/zenoh-buffers/src/zbuf.rs
  commons/zenoh-buffers/src/zslice.rs
  commons/zenoh-buffers/tests/readwrite.rs
  commons/zenoh-codec/src/core/zint.rs
  io/zenoh-transport/src/common/batch.rs
Labels: bug
