Repository eclipse-zenoh/zenoh, pull requests merged in 2024-07, with the labels that each got.

#1213 Fix REST plugin deadlock when too many local replies
  plugins/zenoh-plugin-rest/src/lib.rs
Labels: bug

#1227 Fix typos ("nof" -> "not")
  zenoh/src/net/routing/dispatcher/queries.rs
Labels: enhancement

#1238 Make `rustls`, `rustls-webpki` and `webpki-roots` optional
  io/zenoh-link-commons/Cargo.toml
  io/zenoh-link-commons/src/lib.rs
  io/zenoh-links/zenoh-link-quic/Cargo.toml
  io/zenoh-links/zenoh-link-tls/Cargo.toml
Labels: enhancement

#1191 fix: fix keyexpr canonization unsafe behavior
  commons/zenoh-keyexpr/src/key_expr/canon.rs
  commons/zenoh-keyexpr/src/key_expr/utils.rs
Labels: bug

#1224 Configure `scouting/*/autoconnect/*` with a sequence
  DEFAULT_CONFIG.json5
  commons/zenoh-config/src/lib.rs
  commons/zenoh-config/src/mode_dependent.rs
  commons/zenoh-protocol/src/core/whatami.rs
  zenoh/tests/routing.rs
Labels: enhancement, breaking-change

#1200 Update ACL config format to support AND/OR logic between subjects
  Cargo.lock
  Cargo.toml
  DEFAULT_CONFIG.json5
  commons/zenoh-config/src/defaults.rs
  commons/zenoh-config/src/lib.rs
  zenoh/Cargo.toml
  zenoh/src/net/routing/interceptor/access_control.rs
  zenoh/src/net/routing/interceptor/authorization.rs
  zenoh/tests/acl.rs
  zenoh/tests/authentication.rs
Labels: enhancement, new feature

#1259 Add publisher delete and queryable reply messages to ACL
  DEFAULT_CONFIG.json5
  commons/zenoh-config/src/lib.rs
  zenoh/src/net/routing/interceptor/access_control.rs
  zenoh/src/net/routing/interceptor/authorization.rs
  zenoh/tests/acl.rs
  zenoh/tests/authentication.rs
Labels: new feature

#1270 Fix Clippy errors from Rust 1.80
  Cargo.lock
  clippy.toml
  commons/zenoh-keyexpr/src/keyexpr_tree/mod.rs
  commons/zenoh-keyexpr/src/lib.rs
  zenoh/Cargo.toml
  zenoh/src/api/encoding.rs
  zenoh/src/api/plugins.rs
  zenoh/src/api/session.rs
  zenoh/src/lib.rs
  zenoh/src/net/routing/dispatcher/resource.rs
  zenoh/src/net/routing/interceptor/mod.rs
  zenoh/src/net/runtime/mod.rs
  zenohd/src/main.rs
Labels: bug

#1269 Don't load plugins/volumes when `plugins_loading/enabled:false`
  commons/zenoh-util/src/lib_loader.rs
  plugins/zenoh-plugin-storage-manager/src/lib.rs
  plugins/zenoh-plugin-trait/src/manager.rs
  plugins/zenoh-plugin-trait/src/manager/dynamic_plugin.rs
  plugins/zenoh-plugin-trait/src/manager/static_plugin.rs
  zenoh/src/net/runtime/adminspace.rs
Labels: bug

#1273 Fix Clippy errors from Rust 1.80
  Cargo.lock
  clippy.toml
  zenoh/Cargo.toml
  zenoh/src/key_expr.rs
  zenoh/src/net/routing/dispatcher/resource.rs
  zenoh/src/net/routing/interceptor/mod.rs
  zenoh/src/plugins/sealed.rs
  zenoh/src/session.rs
  zenohd/src/main.rs
Labels: bug

#1275 Don't duplicate token undeclarations in routers
  zenoh/src/net/routing/hat/router/token.rs
Labels: bug

#1266 Optimize RoutingContext keyexpr for Query and Response messages
  zenoh/src/api/session.rs
  zenoh/src/net/primitives/mod.rs
  zenoh/src/net/primitives/mux.rs
  zenoh/src/net/routing/dispatcher/queries.rs
  zenoh/src/net/routing/interceptor/access_control.rs
  zenoh/src/net/runtime/adminspace.rs
  zenoh/src/net/tests/tables.rs
  zenoh/tests/authentication.rs
Labels: enhancement

#1287 fix: invalid mime crash on REST plugin
  plugins/zenoh-plugin-rest/src/lib.rs
Labels: bug

#1283 Fix failing Liveliness Subscriber Undeclaration
  zenoh-ext/tests/liveliness.rs
  zenoh/src/api/session.rs
  zenoh/tests/liveliness.rs
Labels: bug

#1288 Rename `KeyExpr::from_boxed_string_unchecked` to `KeyExpr::from_boxed_str_unchecked`
  commons/zenoh-keyexpr/src/key_expr/owned.rs
  zenoh/src/api/key_expr.rs
  zenoh/src/api/session.rs
Labels: enhancement, breaking-change
