Repository eclipse-zenoh/zenoh, pull requests merged in 2024-10, with the labels that each got.

#1473 feat!: move serialization into zenoh-ext
  Cargo.lock
  Cargo.toml
  ci/valgrind-check/src/pub_sub/bin/z_pub_sub.rs
  ci/valgrind-check/src/queryable_get/bin/z_queryable_get.rs
  commons/zenoh-buffers/src/zbuf.rs
  examples/Cargo.toml
  examples/build.rs
  examples/examples/z_bytes.rs
  examples/examples/z_bytes_shm.rs
  examples/examples/z_get.rs
  examples/examples/z_get_liveliness.rs
  examples/examples/z_get_shm.rs
  examples/examples/z_pub.rs
  examples/examples/z_pull.rs
  examples/examples/z_put_float.rs
  examples/examples/z_queryable.rs
  examples/examples/z_queryable_shm.rs
  examples/examples/z_storage.rs
  examples/examples/z_sub.rs
  examples/examples/z_sub_shm.rs
  plugins/zenoh-plugin-example/src/lib.rs
  plugins/zenoh-plugin-rest/build.rs
  plugins/zenoh-plugin-rest/src/lib.rs
  plugins/zenoh-plugin-storage-manager/build.rs
  plugins/zenoh-plugin-storage-manager/src/replication/aligner.rs
  plugins/zenoh-plugin-storage-manager/src/replication/core.rs
  plugins/zenoh-plugin-storage-manager/src/storages_mgt/service.rs
  plugins/zenoh-plugin-storage-manager/tests/operations.rs
  plugins/zenoh-plugin-storage-manager/tests/wildcard.rs
  zenoh-ext/Cargo.toml
  zenoh-ext/examples/examples/z_query_sub.rs
  zenoh-ext/src/lib.rs
  zenoh-ext/src/serialization.rs
  zenoh-ext/src/session_ext.rs
  zenoh/Cargo.toml
  zenoh/src/api/admin.rs
  zenoh/src/api/builders/publisher.rs
  zenoh/src/api/builders/sample.rs
  zenoh/src/api/bytes.rs
  zenoh/src/api/publisher.rs
  zenoh/src/api/session.rs
  zenoh/src/api/value.rs
  zenoh/src/lib.rs
  zenoh/src/net/runtime/adminspace.rs
  zenoh/tests/acl.rs
  zenoh/tests/attachments.rs
  zenoh/tests/authentication.rs
  zenoh/tests/bytes.rs
  zenoh/tests/handler.rs
  zenoh/tests/shm.rs
Labels: new feature, breaking-change

#1482 Add wait_before_close option
  DEFAULT_CONFIG.json5
  commons/zenoh-config/src/defaults.rs
  commons/zenoh-config/src/lib.rs
  io/zenoh-transport/src/common/pipeline.rs
  io/zenoh-transport/src/manager.rs
  io/zenoh-transport/src/multicast/link.rs
  io/zenoh-transport/src/unicast/universal/link.rs
  io/zenoh-transport/src/unicast/universal/tx.rs
Labels: enhancement

#1487 feat: add `SessionClosed` error
  zenoh/src/api/session.rs
  zenoh/src/lib.rs
Labels: enhancement

#1490 fix: add protobuf example schema
  examples/examples/example.proto
Labels: internal

#1489 fix typos
  commons/zenoh-buffers/src/zslice.rs
  commons/zenoh-keyexpr/src/key_expr/intersect/classical.rs
  commons/zenoh-keyexpr/src/key_expr/intersect/ltr.rs
  commons/zenoh-keyexpr/src/key_expr/intersect/ltr_chunk.rs
  commons/zenoh-keyexpr/src/key_expr/intersect/middle_out.rs
  commons/zenoh-keyexpr/src/key_expr/intersect/mod.rs
  io/zenoh-transport/src/common/batch.rs
  zenoh/src/api/info.rs
Labels: enhancement, release

#1488 Fix cleanup regression
  Cargo.lock
  Cargo.toml
  commons/zenoh-shm/Cargo.toml
  commons/zenoh-shm/src/posix_shm/cleanup.rs
  commons/zenoh-shm/src/posix_shm/mod.rs
  commons/zenoh-shm/src/posix_shm/segment.rs
  commons/zenoh-shm/src/posix_shm/segment_lock.rs
  io/zenoh-links/zenoh-link-unixpipe/Cargo.toml
Labels: bug, release

#1492 chore: make zenoh-ext unstable except serialization
  examples/Cargo.toml
  zenoh-ext/Cargo.toml
  zenoh-ext/examples/Cargo.toml
  zenoh-ext/src/group.rs
  zenoh-ext/src/lib.rs
  zenoh-ext/src/publication_cache.rs
  zenoh-ext/src/querying_subscriber.rs
  zenoh-ext/src/serialization.rs
  zenoh-ext/src/session_ext.rs
  zenoh-ext/src/subscriber_ext.rs
Labels: breaking-change, api fix

#1495 fix: fix zenoh-ext dependencies
  Cargo.lock
  zenoh-ext/Cargo.toml
  zenoh-ext/tests/liveliness.rs
Labels: bug

#1491 Add UNRESPONSIVE close reason
  commons/zenoh-protocol/src/transport/close.rs
  io/zenoh-transport/src/unicast/universal/tx.rs
Labels: internal

#1498 fix: hide varint serialization behind internal feature
  Cargo.lock
  examples/examples/z_bytes.rs
  zenoh-ext/Cargo.toml
  zenoh-ext/src/lib.rs
  zenoh-ext/src/serialization.rs
Labels: internal

#1496 Add missing `transport/multicast` config fields
  DEFAULT_CONFIG.json5
Labels: documentation

#1493 WA for batching problem
  io/zenoh-transport/tests/unicast_transport.rs
Labels: bug, release

#1497 Cleanup only for Linux
  commons/zenoh-shm/src/posix_shm/cleanup.rs
  commons/zenoh-shm/src/posix_shm/mod.rs
  commons/zenoh-shm/src/posix_shm/segment.rs
Labels: enhancement, release, internal

#1503 feat!: renaming of TLS configuration parameters
  DEFAULT_CONFIG.json5
  commons/zenoh-config/src/lib.rs
  io/zenoh-links/zenoh-link-quic/src/lib.rs
  io/zenoh-links/zenoh-link-quic/src/utils.rs
  io/zenoh-links/zenoh-link-tls/src/lib.rs
  io/zenoh-links/zenoh-link-tls/src/utils.rs
  io/zenoh-transport/tests/endpoints.rs
  io/zenoh-transport/tests/unicast_authenticator.rs
  io/zenoh-transport/tests/unicast_multilink.rs
  io/zenoh-transport/tests/unicast_openclose.rs
  io/zenoh-transport/tests/unicast_time.rs
  io/zenoh-transport/tests/unicast_transport.rs
  zenoh/tests/authentication.rs
  zenoh/tests/open_time.rs
Labels: breaking-change

#1514 Add timeout for TLS handshakes
  io/zenoh-links/zenoh-link-tls/src/lib.rs
  io/zenoh-links/zenoh-link-tls/src/unicast.rs
  io/zenoh-links/zenoh-link-tls/src/utils.rs
Labels: bug

#1504 Encapsulate `flume::Receiver`
  Cargo.lock
  plugins/zenoh-plugin-storage-manager/Cargo.toml
  plugins/zenoh-plugin-storage-manager/src/storages_mgt/service.rs
  zenoh-ext/src/publication_cache.rs
  zenoh-ext/src/subscriber_ext.rs
  zenoh/src/api/handlers/fifo.rs
  zenoh/src/api/subscriber.rs
  zenoh/src/lib.rs
  zenoh/tests/matching.rs
Labels: enhancement, breaking-change

#1521 Make FIFO `(try)recv{,_deadline,_timeout}` return `ZResult<Option<T>>`
  zenoh/src/api/handlers/fifo.rs
  zenoh/tests/liveliness.rs
  zenoh/tests/matching.rs
Labels: enhancement, breaking-change

#1520 Encoding and timestamp serialization remove from zenoh-ext
  Cargo.lock
  Cargo.toml
  zenoh-ext/src/serialization.rs
  zenoh/Cargo.toml
  zenoh/src/api/encoding.rs
Labels: breaking-change, internal, api fix

#1510 deadline adoption for multi-fragment message
  io/zenoh-transport/src/common/pipeline.rs
  io/zenoh-transport/tests/unicast_transport.rs
Labels: bug, release, internal

#1516 Fix undesired propagation of interests to routers from peers
  zenoh/src/net/routing/hat/p2p_peer/interests.rs
Labels: internal

#1528 Workaround to fix concurrent transport init bug
  io/zenoh-transport/src/unicast/lowlatency/transport.rs
  io/zenoh-transport/src/unicast/manager.rs
  io/zenoh-transport/src/unicast/transport_unicast_inner.rs
  io/zenoh-transport/src/unicast/universal/transport.rs
Labels: bug, release, internal

#1532 moved builders code into "builders" directory
  zenoh/src/api/admin.rs
  zenoh/src/api/builders/info.rs
  zenoh/src/api/builders/matching_listener.rs
  zenoh/src/api/builders/mod.rs
  zenoh/src/api/builders/publisher.rs
  zenoh/src/api/builders/query.rs
  zenoh/src/api/builders/queryable.rs
  zenoh/src/api/builders/reply.rs
  zenoh/src/api/builders/scouting.rs
  zenoh/src/api/builders/session.rs
  zenoh/src/api/builders/subscriber.rs
  zenoh/src/api/info.rs
  zenoh/src/api/key_expr.rs
  zenoh/src/api/liveliness.rs
  zenoh/src/api/loader.rs
  zenoh/src/api/plugins.rs
  zenoh/src/api/publisher.rs
  zenoh/src/api/query.rs
  zenoh/src/api/queryable.rs
  zenoh/src/api/sample.rs
  zenoh/src/api/scouting.rs
  zenoh/src/api/selector.rs
  zenoh/src/api/session.rs
  zenoh/src/api/subscriber.rs
  zenoh/src/api/value.rs
  zenoh/src/lib.rs
Labels: internal

#1534 readme update
  README.md
Labels: documentation, release

#1535 Add open return conditions options
  DEFAULT_CONFIG.json5
  commons/zenoh-config/src/defaults.rs
  commons/zenoh-config/src/lib.rs
  zenoh/src/net/routing/hat/p2p_peer/gossip.rs
  zenoh/src/net/routing/hat/p2p_peer/interests.rs
  zenoh/src/net/routing/hat/p2p_peer/mod.rs
  zenoh/src/net/runtime/orchestrator.rs
Labels: enhancement

#1538 Fix backoff priority
  io/zenoh-transport/src/common/pipeline.rs
Labels: bug

#1540 docs: add documentation for serialization
  zenoh-ext/src/serialization.rs
  zenoh/src/api/bytes.rs
Labels: documentation

#1541 Fix Clippy errors from Rust 1.82.0
  commons/zenoh-buffers/src/lib.rs
  commons/zenoh-keyexpr/src/key_expr/format/support.rs
Labels: internal

#1543 CI: fix pre-release workflow
  .github/workflows/pre-release.yml
Labels: internal

#1545 Fix QoS extensions naming
  commons/zenoh-codec/src/transport/init.rs
  commons/zenoh-protocol/src/transport/init.rs
  io/zenoh-transport/src/unicast/establishment/accept.rs
  io/zenoh-transport/src/unicast/establishment/ext/qos.rs
  io/zenoh-transport/src/unicast/establishment/open.rs
Labels: internal

#1546 add serialization binary format test
  zenoh-ext/src/serialization.rs
Labels: internal

#1549 Optimize link selection metadata
  commons/zenoh-protocol/src/core/endpoint.rs
  commons/zenoh-protocol/src/core/mod.rs
  io/zenoh-link-commons/src/lib.rs
Labels: enhancement, breaking-change

#1548 Don't close multicast transport on OS error 55
  io/zenoh-links/zenoh-link-udp/src/multicast.rs
Labels: bug

#1550 documentation improvements
  commons/zenoh-util/src/log.rs
  zenoh/src/lib.rs
Labels: documentation, release

#1556 Add SemVer compatibility checks
  .github/workflows/ci.yml
Labels: internal

#1557 Fix bug in return_conditions declares leading to wait for the full delay
  zenoh/src/net/routing/dispatcher/face.rs
  zenoh/src/net/routing/dispatcher/interests.rs
  zenoh/src/net/routing/dispatcher/tables.rs
  zenoh/src/net/routing/hat/client/interests.rs
  zenoh/src/net/routing/hat/linkstate_peer/interests.rs
  zenoh/src/net/routing/hat/mod.rs
  zenoh/src/net/routing/hat/p2p_peer/gossip.rs
  zenoh/src/net/routing/hat/p2p_peer/interests.rs
  zenoh/src/net/routing/hat/p2p_peer/mod.rs
  zenoh/src/net/routing/hat/router/interests.rs
  zenoh/src/net/routing/router.rs
  zenoh/src/net/runtime/orchestrator.rs
Labels: bug

#1559 Do not include zenoh_result::Error in Other AllocError
  commons/zenoh-shm/src/api/provider/types.rs
Labels: bug, enhancement, release

#1561 Add `live-run` input to `bump-crates`
  .github/workflows/release.yml
Labels: internal

#1555 No more MIN_FREE_CHUNK_SIZE limitation
  commons/zenoh-shm/src/api/protocol_implementations/posix/posix_shm_provider_backend.rs
Labels: enhancement, release, internal

#1554 Fix KeepAlive transmission interval
  io/zenoh-transport/src/unicast/universal/link.rs
Labels: internal

#1547 Improve queries routing logging
  zenoh/src/net/routing/dispatcher/queries.rs
Labels: internal

#1566 refactor(storage-manager): replication log lookup
  plugins/zenoh-plugin-storage-manager/src/replication/classification.rs
  plugins/zenoh-plugin-storage-manager/src/replication/core/aligner_query.rs
  plugins/zenoh-plugin-storage-manager/src/replication/core/aligner_reply.rs
  plugins/zenoh-plugin-storage-manager/src/replication/log.rs
  plugins/zenoh-plugin-storage-manager/src/storages_mgt/service.rs
Labels: enhancement

#1567 Don't use the internal config API in zenoh-examples
  examples/src/lib.rs
Labels: enhancement

#1314 Improve test coverage
  zenoh/src/net/primitives/mux.rs
  zenoh/src/net/routing/hat/client/pubsub.rs
  zenoh/tests/routing.rs
Labels: internal

#1574 Fix link selection documentation
  DEFAULT_CONFIG.json5
  commons/zenoh-protocol/src/core/endpoint.rs
Labels: documentation

#1575 fix: fix Liveliness::get lifetime
  zenoh/src/api/liveliness.rs
Labels: enhancement, api fix

#1570 Make TLS link listener accept connections concurrently
  Cargo.lock
  Cargo.toml
  io/zenoh-links/zenoh-link-tls/Cargo.toml
  io/zenoh-links/zenoh-link-tls/src/unicast.rs
Labels: enhancement
