Repository eclipse-zenoh/zenoh, pull requests merged in 2024-05, with the labels that each got.

#1005 fix(compression): adding a workaround to send uncompressed OpenAck
  io/zenoh-transport/src/unicast/link.rs
Labels: bug

#1010 chore: renamed no_mangle feature to dynamic_plugin
  plugins/zenoh-backend-example/Cargo.toml
  plugins/zenoh-backend-example/src/lib.rs
  plugins/zenoh-plugin-example/Cargo.toml
  plugins/zenoh-plugin-example/src/lib.rs
  plugins/zenoh-plugin-rest/Cargo.toml
  plugins/zenoh-plugin-rest/src/lib.rs
  plugins/zenoh-plugin-storage-manager/Cargo.toml
  plugins/zenoh-plugin-storage-manager/src/lib.rs
Labels: enhancement

#1021 Fix bug in Query Timeout
  zenoh/src/net/routing/dispatcher/face.rs
  zenoh/src/net/routing/dispatcher/pubsub.rs
  zenoh/src/net/routing/dispatcher/queries.rs
  zenoh/src/net/tests/tables.rs
Labels: bug

#814 Enhance subscribers, queryables and liveliness tokens propagation to improve scalability
  commons/zenoh-codec/src/network/declare.rs
  commons/zenoh-codec/src/network/interest.rs
  commons/zenoh-protocol/src/network/declare.rs
  commons/zenoh-protocol/src/network/interest.rs
  zenoh/src/api/builders/publication.rs
  zenoh/src/api/publication.rs
  zenoh/src/api/session.rs
  zenoh/src/api/subscriber.rs
  zenoh/src/net/primitives/demux.rs
  zenoh/src/net/primitives/mod.rs
  zenoh/src/net/primitives/mux.rs
  zenoh/src/net/routing/dispatcher/face.rs
  zenoh/src/net/routing/dispatcher/pubsub.rs
  zenoh/src/net/routing/dispatcher/queries.rs
  zenoh/src/net/routing/dispatcher/resource.rs
  zenoh/src/net/routing/hat/client/mod.rs
  zenoh/src/net/routing/hat/client/pubsub.rs
  zenoh/src/net/routing/hat/client/queries.rs
  zenoh/src/net/routing/hat/linkstate_peer/mod.rs
  zenoh/src/net/routing/hat/linkstate_peer/pubsub.rs
  zenoh/src/net/routing/hat/linkstate_peer/queries.rs
  zenoh/src/net/routing/hat/mod.rs
  zenoh/src/net/routing/hat/p2p_peer/mod.rs
  zenoh/src/net/routing/hat/p2p_peer/pubsub.rs
  zenoh/src/net/routing/hat/p2p_peer/queries.rs
  zenoh/src/net/routing/hat/router/mod.rs
  zenoh/src/net/routing/hat/router/pubsub.rs
  zenoh/src/net/routing/hat/router/queries.rs
  zenoh/src/net/runtime/adminspace.rs
  zenoh/src/net/tests/tables.rs
Labels: enhancement

#971 Reduce open time
  commons/zenoh-config/src/defaults.rs
  zenoh/Cargo.toml
  zenoh/src/api/session.rs
  zenoh/src/net/routing/hat/client/mod.rs
  zenoh/src/net/routing/hat/linkstate_peer/mod.rs
  zenoh/src/net/routing/hat/p2p_peer/gossip.rs
  zenoh/src/net/routing/hat/p2p_peer/mod.rs
  zenoh/src/net/routing/hat/p2p_peer/pubsub.rs
  zenoh/src/net/routing/hat/p2p_peer/queries.rs
  zenoh/src/net/routing/hat/router/mod.rs
  zenoh/src/net/runtime/mod.rs
  zenoh/src/net/runtime/orchestrator.rs
  zenoh/tests/open_time.rs
Labels: enhancement

#1039 fix(ci): address the issue of `RUSTUP_WINDOWS_PATH_ADD_BIN` change
  .github/workflows/ci.yml
Labels: internal

#1032 added multicast scouting ttl option
  DEFAULT_CONFIG.json5
  commons/zenoh-config/src/defaults.rs
  commons/zenoh-config/src/lib.rs
  zenoh/src/net/runtime/orchestrator.rs
  zenoh/src/scouting.rs
Labels: new feature

#1058 fix: Relax lifetime bounds in endpoint `as_str` methods
  commons/zenoh-protocol/src/core/endpoint.rs
Labels: enhancement, internal

#1056 fix: replace `Query::reply_err` value parameter by payload
  zenoh/src/api/queryable.rs
  zenoh/tests/session.rs
Labels: internal

#1042 Disable generation of multilink keys if not used
  io/zenoh-transport/src/unicast/establishment/ext/multilink.rs
  io/zenoh-transport/src/unicast/manager.rs
Labels: enhancement
