Repository eclipse-zenoh/zenoh, pull requests merged in 2024-08, with the labels that each got.

#1278 Rework `plugins_loading/search_dirs` config option
  Cargo.lock
  Cargo.toml
  DEFAULT_CONFIG.json5
  commons/zenoh-config/src/lib.rs
  commons/zenoh-util/Cargo.toml
  commons/zenoh-util/src/lib.rs
  commons/zenoh-util/src/lib_loader.rs
  commons/zenoh-util/src/lib_search_dirs.rs
  plugins/zenoh-backend-traits/Cargo.toml
  plugins/zenoh-backend-traits/src/config.rs
  plugins/zenoh-plugin-storage-manager/Cargo.toml
  plugins/zenoh-plugin-storage-manager/src/lib.rs
  zenohd/src/main.rs
Labels: bug, enhancement

#1286 Rename `close` to `undeclare` in `zenoh-ext`
  zenoh-ext/src/publication_cache.rs
  zenoh-ext/src/querying_subscriber.rs
Labels: enhancement, breaking-change

#1296 Fix routing bugs
  zenoh/src/net/routing/hat/client/pubsub.rs
  zenoh/src/net/routing/hat/client/queries.rs
  zenoh/src/net/routing/hat/p2p_peer/pubsub.rs
  zenoh/src/net/routing/hat/p2p_peer/queries.rs
  zenoh/src/net/routing/hat/router/pubsub.rs
  zenoh/src/net/routing/hat/router/queries.rs
  zenoh/src/net/routing/hat/router/token.rs
Labels: bug

#1299 Remove redundant `WhatAmI` tests in `HatBaseTrait::init`
  zenoh/src/net/routing/hat/linkstate_peer/mod.rs
  zenoh/src/net/routing/hat/router/mod.rs
Labels: enhancement

#1341 fix: update check-labels triggers
  .github/workflows/check-labels.yml
Labels: internal
