Repository eclipse-zenoh/zenoh, pull requests merged in 2024-09, with the labels that each got.

#1342 Fix typo
  plugins/zenoh-plugin-trait/src/manager/dynamic_plugin.rs
Labels: internal

#1345 Scouting accepts IPv6 addresses
  zenoh/src/net/runtime/orchestrator.rs
Labels: enhancement

#1346 Fix typos in `JOIN` message specification
  commons/zenoh-protocol/src/transport/join.rs
Labels: internal

#1344 Allow transport defragmentation errors and fix dropping of old transport messages
  io/zenoh-transport/src/common/defragmentation.rs
  io/zenoh-transport/src/multicast/rx.rs
  io/zenoh-transport/src/unicast/universal/rx.rs
  io/zenoh-transport/tests/unicast_defragmentation.rs
Labels: enhancement

#1349 Fix erroneous parsing of `backend_search_dirs`
  plugins/zenoh-backend-traits/src/config.rs
Labels: bug

#1305 Publisher reliability
  commons/zenoh-codec/src/network/mod.rs
  commons/zenoh-codec/src/transport/batch.rs
  commons/zenoh-protocol/src/core/mod.rs
  commons/zenoh-protocol/src/network/mod.rs
  commons/zenoh-protocol/src/transport/frame.rs
  io/zenoh-transport/src/common/batch.rs
  io/zenoh-transport/src/common/pipeline.rs
  zenoh/src/api/admin.rs
  zenoh/src/api/builders/publisher.rs
  zenoh/src/api/builders/sample.rs
  zenoh/src/api/publisher.rs
  zenoh/src/api/sample.rs
  zenoh/src/api/session.rs
  zenoh/src/net/primitives/demux.rs
  zenoh/src/net/primitives/mod.rs
  zenoh/src/net/primitives/mux.rs
  zenoh/src/net/routing/dispatcher/face.rs
  zenoh/src/net/routing/dispatcher/pubsub.rs
  zenoh/src/net/runtime/adminspace.rs
  zenoh/src/net/tests/tables.rs
Labels: new feature

#1354 Add ZBytes::slices
  examples/examples/z_bytes.rs
  zenoh/src/api/bytes.rs
Labels: documentation, new feature

#1361 Encapsulate ZBufSliceIterator in ZBytesSliceIterator
  zenoh/src/api/bytes.rs
Labels: enhancement

#1362 expose ZBytesSliceIterator to public api
  zenoh/src/lib.rs
Labels: release, internal, api fix

#1359 Yeet 73 unused dependencies
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  ci/nostd-check/Cargo.toml
  ci/valgrind-check/Cargo.toml
  commons/zenoh-codec/Cargo.toml
  commons/zenoh-collections/Cargo.toml
  commons/zenoh-config/Cargo.toml
  commons/zenoh-core/Cargo.toml
  commons/zenoh-protocol/Cargo.toml
  commons/zenoh-runtime/Cargo.toml
  commons/zenoh-shm/Cargo.toml
  commons/zenoh-sync/Cargo.toml
  examples/Cargo.toml
  io/zenoh-link-commons/Cargo.toml
  io/zenoh-link/Cargo.toml
  io/zenoh-links/zenoh-link-quic/Cargo.toml
  io/zenoh-links/zenoh-link-serial/Cargo.toml
  io/zenoh-links/zenoh-link-tcp/Cargo.toml
  io/zenoh-links/zenoh-link-tls/Cargo.toml
  io/zenoh-links/zenoh-link-udp/Cargo.toml
  io/zenoh-links/zenoh-link-unixpipe/Cargo.toml
  io/zenoh-links/zenoh-link-unixsock_stream/Cargo.toml
  io/zenoh-links/zenoh-link-vsock/Cargo.toml
  io/zenoh-links/zenoh-link-ws/Cargo.toml
  io/zenoh-transport/Cargo.toml
  plugins/zenoh-backend-example/Cargo.toml
  plugins/zenoh-plugin-example/Cargo.toml
  plugins/zenoh-plugin-rest/Cargo.toml
  plugins/zenoh-plugin-storage-manager/Cargo.toml
  plugins/zenoh-plugin-trait/Cargo.toml
  zenoh-ext/Cargo.toml
  zenoh-ext/examples/Cargo.toml
  zenoh/Cargo.toml
Labels: enhancement

#1365 Apply lints from Clippy 1.81.0
  io/zenoh-links/zenoh-link-tcp/src/unicast.rs
  io/zenoh-links/zenoh-link-vsock/src/unicast.rs
  io/zenoh-transport/src/unicast/establishment/accept.rs
  io/zenoh-transport/src/unicast/establishment/open.rs
Labels: enhancement

#1358 Fix bug with QueryTarget ALL_COMPLETE in clients and peers
  Cargo.lock
  zenoh/Cargo.toml
  zenoh/src/net/routing/dispatcher/queries.rs
  zenoh/src/net/routing/dispatcher/resource.rs
  zenoh/src/net/routing/hat/client/queries.rs
  zenoh/src/net/routing/hat/linkstate_peer/queries.rs
  zenoh/src/net/routing/hat/p2p_peer/queries.rs
  zenoh/src/net/routing/hat/router/queries.rs
Labels: bug

#1370 fix: publisher should not be clonable
  zenoh/src/api/publisher.rs
Labels: bug

#1376 made builder traits internal
  commons/zenoh-macros/src/lib.rs
  plugins/zenoh-plugin-rest/examples/z_serve_sse.rs
  plugins/zenoh-plugin-rest/src/lib.rs
  plugins/zenoh-plugin-storage-manager/src/replica/aligner.rs
  plugins/zenoh-plugin-storage-manager/src/replica/storage.rs
  zenoh-ext/src/querying_subscriber.rs
  zenoh/src/api/builders/publisher.rs
  zenoh/src/api/builders/sample.rs
  zenoh/src/api/query.rs
  zenoh/src/api/queryable.rs
  zenoh/src/lib.rs
  zenoh/src/net/runtime/adminspace.rs
  zenoh/src/prelude.rs
Labels: enhancement, breaking-change

#1374 Fix bugs querying liveliness tokens
  zenoh/src/net/routing/hat/client/token.rs
  zenoh/src/net/routing/hat/p2p_peer/interests.rs
  zenoh/src/net/routing/hat/p2p_peer/mod.rs
  zenoh/src/net/routing/hat/p2p_peer/pubsub.rs
  zenoh/src/net/routing/hat/p2p_peer/queries.rs
  zenoh/src/net/routing/hat/p2p_peer/token.rs
Labels: bug

#1369 refactor: add comment for `Session` and `Session::close`
  zenoh/src/api/publisher.rs
  zenoh/src/api/session.rs
Labels: documentation

#1377 feat: use builder method instead of handler type for undeclaration on drop
  zenoh/src/api/liveliness.rs
  zenoh/src/api/publisher.rs
  zenoh/src/api/queryable.rs
  zenoh/src/api/session.rs
  zenoh/src/api/subscriber.rs
Labels: enhancement

#1355 Add LivelinessSubscriber history option
  examples/examples/z_sub_liveliness.rs
  zenoh/src/api/liveliness.rs
  zenoh/src/api/session.rs
Labels: new feature

#1378 chore: merge main into dev/arcsession
  Cargo.lock
  commons/zenoh-macros/src/lib.rs
  plugins/zenoh-plugin-rest/examples/z_serve_sse.rs
  plugins/zenoh-plugin-rest/src/lib.rs
  plugins/zenoh-plugin-storage-manager/src/replica/aligner.rs
  plugins/zenoh-plugin-storage-manager/src/replica/storage.rs
  zenoh-ext/src/querying_subscriber.rs
  zenoh/Cargo.toml
  zenoh/src/api/builders/publisher.rs
  zenoh/src/api/builders/sample.rs
  zenoh/src/api/publisher.rs
  zenoh/src/api/query.rs
  zenoh/src/api/queryable.rs
  zenoh/src/lib.rs
  zenoh/src/net/routing/dispatcher/queries.rs
  zenoh/src/net/routing/dispatcher/resource.rs
  zenoh/src/net/routing/hat/client/queries.rs
  zenoh/src/net/routing/hat/client/token.rs
  zenoh/src/net/routing/hat/linkstate_peer/queries.rs
  zenoh/src/net/routing/hat/p2p_peer/interests.rs
  zenoh/src/net/routing/hat/p2p_peer/mod.rs
  zenoh/src/net/routing/hat/p2p_peer/pubsub.rs
  zenoh/src/net/routing/hat/p2p_peer/queries.rs
  zenoh/src/net/routing/hat/p2p_peer/token.rs
  zenoh/src/net/routing/hat/router/queries.rs
  zenoh/src/net/runtime/adminspace.rs
  zenoh/src/prelude.rs
Labels: internal

#1381 Close #1357
  io/zenoh-links/zenoh-link-unixsock_stream/src/unicast.rs
Labels: internal

#1373 feat(zenoh_id): exposing into `[u8; 16]` & `to_le_bytes()`
  commons/zenoh-config/src/wrappers.rs
Labels: enhancement

#1382 fix: various fixes
  examples/examples/z_pub.rs
  plugins/zenoh-plugin-storage-manager/src/replica/align_queryable.rs
  zenoh/src/api/publisher.rs
  zenoh/tests/qos.rs
  zenoh/tests/routing.rs
  zenoh/tests/session.rs
  zenoh/tests/shm.rs
  zenoh/tests/unicity.rs
Labels: enhancement

#1385 reexporting methods from QoSBuilderTrait added
  zenoh/src/api/query.rs
  zenoh/src/api/queryable.rs
  zenoh/src/api/sample.rs
Labels: bug

#1391 Fix orchestrator not dying after being killed
  zenoh/src/net/runtime/mod.rs
  zenoh/src/net/runtime/orchestrator.rs
Labels: bug

#1393 feat: add reliability getter to publisher
  zenoh/src/api/publisher.rs
Labels: enhancement

#1389 Enable `shared-memory` feature on docs.rs
  zenoh/Cargo.toml
Labels: enhancement

#1353 Remove subscriber reliability option
  commons/zenoh-codec/src/network/declare.rs
  commons/zenoh-protocol/src/network/declare.rs
  zenoh-ext/src/querying_subscriber.rs
  zenoh-ext/src/subscriber_ext.rs
  zenoh/src/api/session.rs
  zenoh/src/api/subscriber.rs
  zenoh/src/net/routing/dispatcher/face.rs
  zenoh/src/net/routing/dispatcher/pubsub.rs
  zenoh/src/net/routing/dispatcher/resource.rs
  zenoh/src/net/routing/hat/client/pubsub.rs
  zenoh/src/net/routing/hat/linkstate_peer/pubsub.rs
  zenoh/src/net/routing/hat/mod.rs
  zenoh/src/net/routing/hat/p2p_peer/pubsub.rs
  zenoh/src/net/routing/hat/router/pubsub.rs
  zenoh/src/net/runtime/adminspace.rs
  zenoh/src/net/tests/tables.rs
Labels: breaking-change

#1397 res() -> wait()
  commons/zenoh-core/src/lib.rs
  commons/zenoh-shm/src/api/protocol_implementations/posix/posix_shm_provider_backend.rs
  commons/zenoh-shm/src/api/provider/shm_provider.rs
  commons/zenoh-shm/tests/posix_shm_provider.rs
  examples/examples/z_alloc_shm.rs
  examples/examples/z_bytes_shm.rs
  examples/examples/z_get_shm.rs
  examples/examples/z_ping_shm.rs
  examples/examples/z_posix_shm_provider.rs
  examples/examples/z_pub_shm.rs
  examples/examples/z_pub_shm_thr.rs
  examples/examples/z_queryable_shm.rs
  io/zenoh-transport/tests/unicast_shm.rs
  zenoh/src/api/bytes.rs
  zenoh/tests/bytes.rs
  zenoh/tests/shm.rs
Labels: enhancement, breaking-change, release, api fix

#1399 fix(storage-manager): race condition on `latest_updates` structure
  plugins/zenoh-plugin-storage-manager/src/replica/storage.rs
Labels: bug

#1401 `Hello` should be clonable to make it compatible with zenoh-c API
  commons/zenoh-config/src/wrappers.rs
Labels: internal

#1400 Merge branch 'main' into dev/arcsession
  commons/zenoh-codec/src/network/declare.rs
  commons/zenoh-core/src/lib.rs
  commons/zenoh-protocol/src/network/declare.rs
  commons/zenoh-shm/src/api/protocol_implementations/posix/posix_shm_provider_backend.rs
  commons/zenoh-shm/src/api/provider/shm_provider.rs
  commons/zenoh-shm/tests/posix_shm_provider.rs
  examples/examples/z_alloc_shm.rs
  examples/examples/z_bytes_shm.rs
  examples/examples/z_get_shm.rs
  examples/examples/z_ping_shm.rs
  examples/examples/z_posix_shm_provider.rs
  examples/examples/z_pub_shm.rs
  examples/examples/z_pub_shm_thr.rs
  examples/examples/z_queryable_shm.rs
  io/zenoh-transport/tests/unicast_shm.rs
  zenoh-ext/src/querying_subscriber.rs
  zenoh-ext/src/subscriber_ext.rs
  zenoh/Cargo.toml
  zenoh/src/api/bytes.rs
  zenoh/src/api/publisher.rs
  zenoh/src/api/session.rs
  zenoh/src/api/subscriber.rs
  zenoh/src/net/routing/dispatcher/face.rs
  zenoh/src/net/routing/dispatcher/pubsub.rs
  zenoh/src/net/routing/dispatcher/resource.rs
  zenoh/src/net/routing/hat/client/pubsub.rs
  zenoh/src/net/routing/hat/linkstate_peer/pubsub.rs
  zenoh/src/net/routing/hat/mod.rs
  zenoh/src/net/routing/hat/p2p_peer/pubsub.rs
  zenoh/src/net/routing/hat/router/pubsub.rs
  zenoh/src/net/runtime/adminspace.rs
  zenoh/src/net/tests/tables.rs
  zenoh/tests/bytes.rs
  zenoh/tests/shm.rs
Labels: enhancement

#1394 Support `--cfg` flag in examples
  examples/src/lib.rs
Labels: new feature

#1403 refactor: use builder method for undeclaration on drop
  zenoh-ext/src/querying_subscriber.rs
  zenoh-ext/src/subscriber_ext.rs
  zenoh/src/api/handlers/callback.rs
  zenoh/src/api/handlers/mod.rs
  zenoh/src/api/liveliness.rs
  zenoh/src/api/publisher.rs
  zenoh/src/api/query.rs
  zenoh/src/api/queryable.rs
  zenoh/src/api/session.rs
  zenoh/src/api/subscriber.rs
Labels: enhancement

#1396 Don't auto-connect to configured connect endpoints
  zenoh/src/net/runtime/orchestrator.rs
Labels: bug

#1407 refactor: remove state from entities
  zenoh/src/api/admin.rs
  zenoh/src/api/builders/publisher.rs
  zenoh/src/api/liveliness.rs
  zenoh/src/api/publisher.rs
  zenoh/src/api/queryable.rs
  zenoh/src/api/session.rs
  zenoh/src/api/subscriber.rs
Labels: enhancement

#1404 Bug/liveliness duplicate
  zenoh/src/api/session.rs
  zenoh/src/net/routing/hat/client/token.rs
  zenoh/src/net/routing/hat/linkstate_peer/pubsub.rs
  zenoh/src/net/routing/hat/linkstate_peer/queries.rs
  zenoh/src/net/routing/hat/linkstate_peer/token.rs
  zenoh/src/net/routing/hat/p2p_peer/pubsub.rs
  zenoh/src/net/routing/hat/p2p_peer/queries.rs
  zenoh/src/net/routing/hat/p2p_peer/token.rs
  zenoh/src/net/routing/hat/router/pubsub.rs
  zenoh/src/net/routing/hat/router/queries.rs
  zenoh/src/net/routing/hat/router/token.rs
Labels: bug

#1412 fix: remove `Session::put` onehost publisher
  zenoh/src/api/builders/publisher.rs
  zenoh/src/api/publisher.rs
  zenoh/src/api/session.rs
Labels: bug

#1410 fix: update release workflow to depend on cargo
  .github/workflows/release.yml
Labels: internal

#1416 Bugfix (rest-plugins): Correct the return type of if-condition to ensure zenohd get the error.
  DEFAULT_CONFIG.json5
  plugins/zenoh-plugin-rest/src/lib.rs
Labels: bug

#1421 Make SHM Alloc builders naming more friendly
  commons/zenoh-shm/src/api/provider/shm_provider.rs
  zenoh/src/lib.rs
Labels: documentation, enhancement, release, api fix

#1420 Add more liveliness tests
  zenoh/tests/liveliness.rs
Labels: internal

#1427 Mark session.uhlc as internal
  zenoh/src/api/session.rs
Labels: breaking-change

#1429 Put cleanup API to the prelude
  zenoh/src/lib.rs
Labels: enhancement, release, api fix

#1428 Clarify batch size requirement when operating on multicast
  DEFAULT_CONFIG.json5
Labels: documentation

#1419 Hide `zenoh_config` internals
  Cargo.lock
  commons/zenoh-config/Cargo.toml
  commons/zenoh-config/src/defaults.rs
  commons/zenoh-config/src/lib.rs
  commons/zenoh-macros/src/lib.rs
  examples/src/lib.rs
  zenoh-ext/Cargo.toml
  zenoh-ext/examples/Cargo.toml
  zenoh-ext/examples/examples/z_pub_cache.rs
  zenoh-ext/examples/src/lib.rs
  zenoh-ext/src/querying_subscriber.rs
  zenoh-ext/src/session_ext.rs
  zenoh-ext/src/subscriber_ext.rs
  zenoh-ext/tests/liveliness.rs
  zenoh/Cargo.toml
  zenoh/src/api/builders/publisher.rs
  zenoh/src/api/config.rs
  zenoh/src/api/info.rs
  zenoh/src/api/key_expr.rs
  zenoh/src/api/liveliness.rs
  zenoh/src/api/mod.rs
  zenoh/src/api/publisher.rs
  zenoh/src/api/query.rs
  zenoh/src/api/queryable.rs
  zenoh/src/api/scouting.rs
  zenoh/src/api/session.rs
  zenoh/src/api/subscriber.rs
  zenoh/src/lib.rs
  zenoh/src/net/routing/hat/linkstate_peer/mod.rs
  zenoh/src/net/routing/hat/p2p_peer/mod.rs
  zenoh/src/net/routing/hat/router/mod.rs
  zenoh/src/net/runtime/adminspace.rs
  zenoh/src/net/runtime/mod.rs
  zenoh/src/net/runtime/orchestrator.rs
  zenoh/tests/acl.rs
  zenoh/tests/authentication.rs
  zenoh/tests/connection_retry.rs
  zenoh/tests/events.rs
  zenoh/tests/interceptors.rs
  zenoh/tests/liveliness.rs
  zenoh/tests/matching.rs
  zenoh/tests/open_time.rs
  zenoh/tests/qos.rs
  zenoh/tests/routing.rs
  zenoh/tests/session.rs
  zenoh/tests/shm.rs
  zenoh/tests/unicity.rs
  zenohd/Cargo.toml
  zenohd/src/main.rs
Labels: bug, breaking-change

#1422 feat: improving pluging feature
  Cargo.lock
  Cargo.toml
  plugins/zenoh-plugin-rest/Cargo.toml
  plugins/zenoh-plugin-trait/Cargo.toml
  plugins/zenoh-plugin-trait/src/lib.rs
  plugins/zenoh-plugin-trait/src/plugin.rs
  zenoh/Cargo.toml
  zenoh/src/net/runtime/adminspace.rs
  zenoh/src/net/runtime/mod.rs
  zenohd/Cargo.toml
Labels: enhancement, internal

#1431 Adopt accessor pattern for Selector
  zenoh/src/api/selector.rs
Labels: breaking-change, api sync

#1424 Update depdendencies
  Cargo.lock
  Cargo.toml
Labels: enhancement, internal

#1434 Adopt accessors pattern for SourceInfo
  zenoh/src/api/sample.rs
Labels: breaking-change, api sync

#1437 Make `zenoh::session::ZenohId` stable
  zenoh/src/lib.rs
Labels: bug, breaking-change

#1436 Fix config rexport
  Cargo.lock
  commons/zenoh-macros/src/lib.rs
  zenoh/Cargo.toml
  zenoh/src/api/config.rs
  zenoh/src/lib.rs
  zenoh/tests/acl.rs
  zenoh/tests/authentication.rs
  zenoh/tests/connection_retry.rs
  zenoh/tests/events.rs
  zenoh/tests/interceptors.rs
  zenoh/tests/open_time.rs
  zenoh/tests/routing.rs
  zenoh/tests/session.rs
  zenoh/tests/unicity.rs
Labels: internal

#1440 Revert cleanup
  Cargo.lock
  Cargo.toml
  commons/zenoh-shm/Cargo.toml
  commons/zenoh-shm/src/api/cleanup.rs
  commons/zenoh-shm/src/api/mod.rs
  commons/zenoh-shm/src/cleanup.rs
  commons/zenoh-shm/tests/watchdog.rs
  zenoh/src/lib.rs
Labels: bug

#1441 Make `LivelinessToken` `#[must_use]`
  zenoh/src/api/liveliness.rs
Labels: enhancement

#1439 Implement `Error` on `ReplyError`
  zenoh/src/api/query.rs
Labels: enhancement

#1442 Fix Selector lifetime
  zenoh/src/api/selector.rs
Labels: internal

#1448 fix: put `SourceSn` behind unstable
  zenoh/src/lib.rs
Labels: internal

#1449 Notify subscribers on `Notifier<Config>::insert_json5`
  zenoh/src/api/config.rs
Labels: bug, internal

#1447 Hide `zenoh_buffers::reader::DidntRead`
  Cargo.lock
  zenoh/src/api/bytes.rs
Labels: bug, breaking-change

#1451 Add README for internal crates
  commons/zenoh-runtime/README.md
  commons/zenoh-task/README.md
  io/zenoh-links/zenoh-link-quic/README.md
  io/zenoh-links/zenoh-link-serial/README.md
  io/zenoh-links/zenoh-link-tcp/README.md
  io/zenoh-links/zenoh-link-tls/README.md
  io/zenoh-links/zenoh-link-udp/README.md
  io/zenoh-links/zenoh-link-unixpipe/README.md
  io/zenoh-links/zenoh-link-unixsock_stream/README.md
  io/zenoh-links/zenoh-link-vsock/README.md
  io/zenoh-links/zenoh-link-ws/README.md
  zenoh-ext/README.md
Labels: documentation

#1455 Dev/rustdoc
  commons/zenoh-buffers/src/lib.rs
  commons/zenoh-codec/src/lib.rs
  commons/zenoh-collections/src/lib.rs
  commons/zenoh-core/src/lib.rs
  commons/zenoh-crypto/src/lib.rs
  commons/zenoh-macros/src/lib.rs
  commons/zenoh-macros/src/zenoh_runtime_derive.rs
  commons/zenoh-protocol/src/lib.rs
  commons/zenoh-result/src/lib.rs
  commons/zenoh-sync/src/lib.rs
  commons/zenoh-task/src/lib.rs
  commons/zenoh-util/src/lib.rs
  io/zenoh-link-commons/src/lib.rs
  io/zenoh-link/src/lib.rs
  io/zenoh-links/zenoh-link-quic/src/lib.rs
  io/zenoh-links/zenoh-link-serial/src/lib.rs
  io/zenoh-links/zenoh-link-tcp/src/lib.rs
  io/zenoh-links/zenoh-link-tls/src/lib.rs
  io/zenoh-links/zenoh-link-udp/src/lib.rs
  io/zenoh-links/zenoh-link-unixpipe/src/lib.rs
  io/zenoh-links/zenoh-link-unixpipe/src/unix/mod.rs
  io/zenoh-links/zenoh-link-unixsock_stream/src/lib.rs
  io/zenoh-links/zenoh-link-vsock/src/lib.rs
  io/zenoh-links/zenoh-link-ws/src/lib.rs
  io/zenoh-transport/src/lib.rs
  plugins/zenoh-plugin-rest/src/lib.rs
  plugins/zenoh-plugin-storage-manager/src/lib.rs
  zenoh-ext/src/querying_subscriber.rs
  zenoh/src/api/builders/publisher.rs
  zenoh/src/api/liveliness.rs
  zenoh/src/api/publisher.rs
  zenoh/src/api/query.rs
  zenoh/src/api/queryable.rs
  zenoh/src/api/session.rs
  zenoh/src/api/subscriber.rs
  zenoh/src/net/mod.rs
  zenoh/src/net/routing/dispatcher/mod.rs
  zenoh/src/net/routing/hat/client/mod.rs
  zenoh/src/net/routing/hat/linkstate_peer/mod.rs
  zenoh/src/net/routing/hat/mod.rs
  zenoh/src/net/routing/hat/p2p_peer/mod.rs
  zenoh/src/net/routing/hat/router/mod.rs
  zenoh/src/net/routing/interceptor/access_control.rs
  zenoh/src/net/routing/interceptor/authorization.rs
  zenoh/src/net/routing/interceptor/downsampling.rs
  zenoh/src/net/routing/interceptor/mod.rs
  zenoh/src/net/routing/mod.rs
  zenoh/src/net/runtime/mod.rs
Labels: documentation

#1452 Fix keyexpr_tree lifetime
  commons/zenoh-keyexpr/src/keyexpr_tree/traits/mod.rs
Labels: internal

#1450 Fix liveliness bugs
  commons/zenoh-protocol/src/network/interest.rs
  zenoh/src/api/session.rs
  zenoh/src/net/routing/dispatcher/interests.rs
  zenoh/src/net/routing/hat/client/interests.rs
  zenoh/src/net/routing/hat/client/token.rs
  zenoh/src/net/routing/hat/linkstate_peer/pubsub.rs
  zenoh/src/net/routing/hat/linkstate_peer/queries.rs
  zenoh/src/net/routing/hat/linkstate_peer/token.rs
  zenoh/src/net/routing/hat/p2p_peer/interests.rs
  zenoh/src/net/routing/hat/p2p_peer/mod.rs
  zenoh/src/net/routing/hat/p2p_peer/pubsub.rs
  zenoh/src/net/routing/hat/p2p_peer/queries.rs
  zenoh/src/net/routing/hat/p2p_peer/token.rs
  zenoh/src/net/routing/hat/router/pubsub.rs
  zenoh/src/net/routing/hat/router/queries.rs
  zenoh/src/net/routing/hat/router/token.rs
  zenoh/tests/liveliness.rs
Labels: bug

#1457 Reliability is exported in zenoh::qos
  zenoh-ext/src/querying_subscriber.rs
  zenoh/src/api/subscriber.rs
  zenoh/src/lib.rs
  zenoh/tests/session.rs
  zenoh/tests/shm.rs
Labels: internal

#1454 refactor(storage-manager): implement cache for `History::Latest`
  plugins/zenoh-backend-example/src/lib.rs
  plugins/zenoh-backend-traits/src/lib.rs
  plugins/zenoh-plugin-storage-manager/src/memory_backend/mod.rs
  plugins/zenoh-plugin-storage-manager/src/storages_mgt/mod.rs
  plugins/zenoh-plugin-storage-manager/src/storages_mgt/service.rs
Labels: enhancement

#1456 Downgrade some connectivity error traces to warning
  zenoh/src/net/runtime/orchestrator.rs
Labels: internal

#1460 Fix router to router key expressions mapping
  zenoh/src/net/routing/hat/router/interests.rs
Labels: internal

#1459 chore: Update jsonschema to 0.20.0
  Cargo.lock
  Cargo.toml
  plugins/zenoh-plugin-rest/build.rs
  plugins/zenoh-plugin-storage-manager/build.rs
Labels: dependencies

#1461 Align TimeRange struct to std::ops::Range
  commons/zenoh-util/src/time_range.rs
Labels: breaking-change

#1462 Polish the public API
  commons/zenoh-core/src/lib.rs
  commons/zenoh-keyexpr/src/key_expr/format/mod.rs
  commons/zenoh-protocol/src/core/mod.rs
  commons/zenoh-shm/src/api/provider/types.rs
  commons/zenoh-util/src/log.rs
  zenoh-ext/src/publication_cache.rs
  zenoh-ext/src/querying_subscriber.rs
  zenoh/src/api/builders/publisher.rs
  zenoh/src/api/bytes.rs
  zenoh/src/api/info.rs
  zenoh/src/api/key_expr.rs
  zenoh/src/api/liveliness.rs
  zenoh/src/api/publisher.rs
  zenoh/src/api/query.rs
  zenoh/src/api/queryable.rs
  zenoh/src/api/scouting.rs
  zenoh/src/api/session.rs
  zenoh/src/api/subscriber.rs
  zenoh/src/lib.rs
  zenoh/src/prelude.rs
Labels: documentation, enhancement, breaking-change

#1465 Remove misplaced `#[cfg(feature = "unstable")]`
  zenoh-ext/src/querying_subscriber.rs
Labels: internal

#1458 feat: rewrite of Storage Replication
  Cargo.lock
  DEFAULT_CONFIG.json5
  deny.toml
  plugins/zenoh-backend-traits/src/config.rs
  plugins/zenoh-backend-traits/src/config.test.rs
  plugins/zenoh-backend-traits/src/lib.rs
  plugins/zenoh-plugin-storage-manager/Cargo.toml
  plugins/zenoh-plugin-storage-manager/src/lib.rs
  plugins/zenoh-plugin-storage-manager/src/replication/aligner.rs
  plugins/zenoh-plugin-storage-manager/src/replication/classification.rs
  plugins/zenoh-plugin-storage-manager/src/replication/configuration.rs
  plugins/zenoh-plugin-storage-manager/src/replication/core.rs
  plugins/zenoh-plugin-storage-manager/src/replication/digest.rs
  plugins/zenoh-plugin-storage-manager/src/replication/log.rs
  plugins/zenoh-plugin-storage-manager/src/replication/mod.rs
  plugins/zenoh-plugin-storage-manager/src/replication/service.rs
  plugins/zenoh-plugin-storage-manager/src/replication/tests/classification.test.rs
  plugins/zenoh-plugin-storage-manager/src/replication/tests/configuration.test.rs
  plugins/zenoh-plugin-storage-manager/src/replication/tests/digest.test.rs
  plugins/zenoh-plugin-storage-manager/src/replication/tests/log.test.rs
  plugins/zenoh-plugin-storage-manager/src/storages_mgt/mod.rs
  plugins/zenoh-plugin-storage-manager/src/storages_mgt/service.rs
  zenoh/src/api/sample.rs
Labels: new feature

#1398 Select links based on message Priority & Reliability
  DEFAULT_CONFIG.json5
  commons/zenoh-codec/src/transport/init.rs
  commons/zenoh-protocol/src/core/endpoint.rs
  commons/zenoh-protocol/src/core/locator.rs
  commons/zenoh-protocol/src/core/mod.rs
  commons/zenoh-protocol/src/transport/init.rs
  io/zenoh-link-commons/src/lib.rs
  io/zenoh-link-commons/src/unicast.rs
  io/zenoh-link/src/lib.rs
  io/zenoh-links/zenoh-link-quic/src/lib.rs
  io/zenoh-links/zenoh-link-quic/src/unicast.rs
  io/zenoh-links/zenoh-link-serial/src/lib.rs
  io/zenoh-links/zenoh-link-serial/src/unicast.rs
  io/zenoh-links/zenoh-link-tcp/src/lib.rs
  io/zenoh-links/zenoh-link-tcp/src/unicast.rs
  io/zenoh-links/zenoh-link-tls/src/lib.rs
  io/zenoh-links/zenoh-link-tls/src/unicast.rs
  io/zenoh-links/zenoh-link-udp/src/lib.rs
  io/zenoh-links/zenoh-link-udp/src/unicast.rs
  io/zenoh-links/zenoh-link-unixpipe/src/unix/mod.rs
  io/zenoh-links/zenoh-link-unixpipe/src/unix/unicast.rs
  io/zenoh-links/zenoh-link-unixsock_stream/src/lib.rs
  io/zenoh-links/zenoh-link-unixsock_stream/src/unicast.rs
  io/zenoh-links/zenoh-link-vsock/src/lib.rs
  io/zenoh-links/zenoh-link-vsock/src/unicast.rs
  io/zenoh-links/zenoh-link-ws/src/lib.rs
  io/zenoh-links/zenoh-link-ws/src/unicast.rs
  io/zenoh-transport/src/manager.rs
  io/zenoh-transport/src/multicast/link.rs
  io/zenoh-transport/src/multicast/mod.rs
  io/zenoh-transport/src/multicast/transport.rs
  io/zenoh-transport/src/unicast/establishment/accept.rs
  io/zenoh-transport/src/unicast/establishment/ext/qos.rs
  io/zenoh-transport/src/unicast/establishment/open.rs
  io/zenoh-transport/src/unicast/link.rs
  io/zenoh-transport/src/unicast/lowlatency/link.rs
  io/zenoh-transport/src/unicast/manager.rs
  io/zenoh-transport/src/unicast/universal/link.rs
  io/zenoh-transport/src/unicast/universal/transport.rs
  io/zenoh-transport/src/unicast/universal/tx.rs
  zenoh/src/net/runtime/mod.rs
  zenoh/src/net/runtime/orchestrator.rs
Labels: enhancement, new feature

#1475 do not use Linux Ephemeral ports in tests
  zenoh/tests/authentication.rs
  zenoh/tests/interceptors.rs
  zenoh/tests/unicity.rs
Labels: enhancement, release

#1478 fix: starting rest plugin like any other plugin
  plugins/zenoh-plugin-rest/src/lib.rs
Labels: bug

#1479 chore: update release.yml for required labels
  .github/release.yml
Labels: internal

#1445 Alternative SHM segment cleanup
  commons/zenoh-shm/src/api/cleanup.rs
  commons/zenoh-shm/src/api/mod.rs
  commons/zenoh-shm/src/cleanup.rs
  commons/zenoh-shm/src/posix_shm/cleanup.rs
  commons/zenoh-shm/src/posix_shm/mod.rs
  commons/zenoh-shm/src/posix_shm/segment.rs
  zenoh/src/lib.rs
Labels: bug, release

#1477 Fix peers start conditions bug
  zenoh/src/net/routing/hat/p2p_peer/gossip.rs
  zenoh/src/net/runtime/orchestrator.rs
Labels: internal

#1469 Remove closing from hat trait
  io/zenoh-transport/src/lib.rs
  io/zenoh-transport/src/multicast/transport.rs
  io/zenoh-transport/src/unicast/lowlatency/transport.rs
  io/zenoh-transport/src/unicast/universal/transport.rs
  io/zenoh-transport/tests/endpoints.rs
  io/zenoh-transport/tests/multicast_compression.rs
  io/zenoh-transport/tests/multicast_transport.rs
  io/zenoh-transport/tests/transport_whitelist.rs
  io/zenoh-transport/tests/unicast_authenticator.rs
  io/zenoh-transport/tests/unicast_compression.rs
  io/zenoh-transport/tests/unicast_concurrent.rs
  io/zenoh-transport/tests/unicast_intermittent.rs
  io/zenoh-transport/tests/unicast_priorities.rs
  io/zenoh-transport/tests/unicast_shm.rs
  io/zenoh-transport/tests/unicast_simultaneous.rs
  io/zenoh-transport/tests/unicast_transport.rs
  zenoh/src/api/admin.rs
  zenoh/src/net/primitives/demux.rs
  zenoh/src/net/primitives/mux.rs
  zenoh/src/net/routing/dispatcher/face.rs
  zenoh/src/net/routing/dispatcher/tables.rs
  zenoh/src/net/routing/hat/client/mod.rs
  zenoh/src/net/routing/hat/linkstate_peer/mod.rs
  zenoh/src/net/routing/hat/mod.rs
  zenoh/src/net/routing/hat/p2p_peer/mod.rs
  zenoh/src/net/routing/hat/router/mod.rs
  zenoh/src/net/runtime/mod.rs
  zenoh/src/net/runtime/orchestrator.rs
  zenoh/src/net/tests/tables.rs
Labels: internal

#1476 Send Declare and OAM messages with Control priority
  commons/zenoh-protocol/src/network/mod.rs
Labels: enhancement

#1480 Improve performances when wait_before_drop is 0
  io/zenoh-transport/src/common/pipeline.rs
Labels: enhancement

#1484 fix: using spawn_runtime instead of tokio::spawn
  plugins/zenoh-plugin-rest/src/lib.rs
Labels: bug

#1486 Routing refactoring I
  commons/zenoh-protocol/src/core/wire_expr.rs
  commons/zenoh-protocol/src/network/interest.rs
  zenoh/src/net/routing/dispatcher/interests.rs
  zenoh/src/net/routing/hat/client/interests.rs
  zenoh/src/net/routing/hat/client/mod.rs
  zenoh/src/net/routing/hat/client/token.rs
  zenoh/src/net/routing/hat/linkstate_peer/interests.rs
  zenoh/src/net/routing/hat/linkstate_peer/mod.rs
  zenoh/src/net/routing/hat/linkstate_peer/pubsub.rs
  zenoh/src/net/routing/hat/linkstate_peer/queries.rs
  zenoh/src/net/routing/hat/linkstate_peer/token.rs
  zenoh/src/net/routing/hat/p2p_peer/interests.rs
  zenoh/src/net/routing/hat/p2p_peer/mod.rs
  zenoh/src/net/routing/hat/p2p_peer/pubsub.rs
  zenoh/src/net/routing/hat/p2p_peer/queries.rs
  zenoh/src/net/routing/hat/p2p_peer/token.rs
  zenoh/src/net/routing/hat/router/interests.rs
  zenoh/src/net/routing/hat/router/mod.rs
  zenoh/src/net/routing/hat/router/pubsub.rs
  zenoh/src/net/routing/hat/router/queries.rs
  zenoh/src/net/routing/hat/router/token.rs
Labels: internal
