Repository eclipse-zenoh/zenoh, pull requests merged in 2024-11, with the labels that each got.

#1578 fix: break fragment chain when dropping fragmented message
  commons/zenoh-shm/src/api/provider/types.rs
  commons/zenoh-shm/src/lib.rs
  examples/README.md
  io/zenoh-transport/src/common/pipeline.rs
  plugins/zenoh-plugin-trait/src/lib.rs
Labels: bug

#1577 remove obsolete zenoh::internal::Value
  plugins/zenoh-backend-example/src/lib.rs
  plugins/zenoh-backend-traits/src/lib.rs
  plugins/zenoh-plugin-storage-manager/src/memory_backend/mod.rs
  plugins/zenoh-plugin-storage-manager/src/replication/core/aligner_query.rs
  plugins/zenoh-plugin-storage-manager/src/replication/core/aligner_reply.rs
  plugins/zenoh-plugin-storage-manager/src/storages_mgt/service.rs
  zenoh/src/api/builders/query.rs
  zenoh/src/api/builders/reply.rs
  zenoh/src/api/mod.rs
  zenoh/src/api/query.rs
  zenoh/src/api/queryable.rs
  zenoh/src/api/sample.rs
  zenoh/src/api/session.rs
  zenoh/src/api/value.rs
  zenoh/src/lib.rs
  zenoh/src/net/runtime/adminspace.rs
Labels: internal, api fix

#1585 fix: do not drop callbacks with session lock held
  zenoh/src/api/session.rs
Labels: bug

#1579 Provide a clearer panic log while missing TLS
  commons/zenoh-runtime/src/lib.rs
Labels: enhancement

#1573 Fix(ACL): Apply queryable and subscriber declaration filters on their respective undeclarations
  zenoh/src/net/routing/dispatcher/pubsub.rs
  zenoh/src/net/routing/dispatcher/queries.rs
  zenoh/src/net/routing/interceptor/access_control.rs
Labels: bug

#1586 fix small bug in backoff update
  io/zenoh-transport/src/common/pipeline.rs
Labels: bug, release, internal

#1592 Do not use ephemeral ports in tests
  zenoh/tests/liveliness.rs
Labels: enhancement, release, internal

#1595 Fix CI badge
  README.md
Labels: internal

#1564 Close TLS and Quic links on certificate expiration
  Cargo.lock
  Cargo.toml
  DEFAULT_CONFIG.json5
  commons/zenoh-config/src/lib.rs
  io/zenoh-link-commons/Cargo.toml
  io/zenoh-link-commons/src/tls.rs
  io/zenoh-links/zenoh-link-quic/Cargo.toml
  io/zenoh-links/zenoh-link-quic/src/lib.rs
  io/zenoh-links/zenoh-link-quic/src/unicast.rs
  io/zenoh-links/zenoh-link-quic/src/utils.rs
  io/zenoh-links/zenoh-link-tls/Cargo.toml
  io/zenoh-links/zenoh-link-tls/src/lib.rs
  io/zenoh-links/zenoh-link-tls/src/unicast.rs
  io/zenoh-links/zenoh-link-tls/src/utils.rs
Labels: enhancement

#1594 feat(ACL): Add liveliness token filters
  DEFAULT_CONFIG.json5
  commons/zenoh-config/src/lib.rs
  zenoh/src/api/session.rs
  zenoh/src/net/routing/dispatcher/token.rs
  zenoh/src/net/routing/hat/client/interests.rs
  zenoh/src/net/routing/hat/p2p_peer/interests.rs
  zenoh/src/net/routing/interceptor/access_control.rs
  zenoh/src/net/routing/interceptor/authorization.rs
  zenoh/tests/acl.rs
Labels: new feature

#1607 Add trace log while dropping the messages.
  io/zenoh-transport/src/common/pipeline.rs
Labels: internal

#1601 Fix version macro & config deserialisation.
  commons/zenoh-config/src/mode_dependent.rs
  plugins/zenoh-plugin-trait/src/lib.rs
  plugins/zenoh-plugin-trait/src/plugin.rs
Labels: internal

#1603 implement non-linear wait before drop(close)
  DEFAULT_CONFIG.json5
  commons/zenoh-config/src/defaults.rs
  commons/zenoh-config/src/lib.rs
  io/zenoh-transport/src/common/pipeline.rs
  io/zenoh-transport/src/manager.rs
Labels: enhancement, release

#1615 Fix message storm when using multiple peers with multicast
  zenoh/src/net/routing/dispatcher/pubsub.rs
  zenoh/src/net/routing/hat/client/mod.rs
  zenoh/src/net/routing/hat/linkstate_peer/mod.rs
  zenoh/src/net/routing/hat/p2p_peer/mod.rs
  zenoh/src/net/routing/hat/p2p_peer/pubsub.rs
  zenoh/src/net/routing/hat/router/mod.rs
Labels: bug

#1618 Fix clippy warnings
  commons/zenoh-buffers/src/slice.rs
  commons/zenoh-buffers/src/vec.rs
  commons/zenoh-buffers/src/zbuf.rs
  commons/zenoh-collections/src/single_or_vec.rs
  commons/zenoh-keyexpr/src/key_expr/borrowed.rs
  commons/zenoh-keyexpr/src/key_expr/format/support.rs
  commons/zenoh-keyexpr/src/key_expr/utils.rs
  commons/zenoh-keyexpr/src/keyexpr_tree/traits/default_impls.rs
  commons/zenoh-protocol/src/core/cowstr.rs
  commons/zenoh-protocol/src/transport/close.rs
  commons/zenoh-protocol/src/transport/fragment.rs
  commons/zenoh-protocol/src/transport/frame.rs
  commons/zenoh-protocol/src/transport/init.rs
  commons/zenoh-protocol/src/transport/keepalive.rs
  commons/zenoh-protocol/src/transport/open.rs
  commons/zenoh-shm/src/api/provider/shm_provider.rs
  commons/zenoh-shm/tests/posix_array.rs
  commons/zenoh-util/src/time_range.rs
  io/zenoh-transport/src/manager.rs
  io/zenoh-transport/src/unicast/establishment/ext/auth/pubkey.rs
  io/zenoh-transport/src/unicast/establishment/ext/auth/usrpwd.rs
  io/zenoh-transport/src/unicast/establishment/ext/compression.rs
  io/zenoh-transport/src/unicast/establishment/ext/lowlatency.rs
  io/zenoh-transport/src/unicast/establishment/ext/qos.rs
  io/zenoh-transport/src/unicast/establishment/ext/shm.rs
  plugins/zenoh-plugin-rest/src/config.rs
  zenoh-ext/src/querying_subscriber.rs
  zenoh/src/api/builders/info.rs
  zenoh/src/api/builders/publisher.rs
  zenoh/src/api/builders/query.rs
  zenoh/src/api/builders/reply.rs
  zenoh/src/api/config.rs
  zenoh/src/api/handlers/fifo.rs
  zenoh/src/api/key_expr.rs
  zenoh/src/api/publisher.rs
  zenoh/src/lib.rs
  zenoh/tests/liveliness.rs
Labels: internal

#1619 Fix bug declaring/undeclaring tokens with the same key
  zenoh/src/api/liveliness.rs
  zenoh/src/api/session.rs
  zenoh/tests/liveliness.rs
Labels: bug
