Repository eclipse-zenoh/zenoh, pull requests merged in 2025-04, with the labels that each got.

#1866 Make SHM segment cleanup routine more robust
  commons/zenoh-shm/src/shm/mod.rs
  commons/zenoh-shm/src/shm/unix.rs
Labels: enhancement, release

#1867 Fix memory leak in shm segment cleanup
  commons/zenoh-shm/src/cleanup.rs
  commons/zenoh-shm/src/posix_shm/segment.rs
  commons/zenoh-shm/src/shm/mod.rs
Labels: bug, release

#1868 Add low pass filter
  DEFAULT_CONFIG.json5
  commons/zenoh-config/src/lib.rs
  zenoh/src/net/routing/interceptor/low_pass.rs
  zenoh/src/net/routing/interceptor/mod.rs
  zenoh/tests/low_pass.rs
Labels: new feature

#1874 Fix identation in rustdoc comments
  io/zenoh-transport/src/common/seq_num.rs
  plugins/zenoh-plugin-trait/src/vtable.rs
Labels: bug

#1875 Revert "Improve batching wait on multifragment messages"
  io/zenoh-transport/src/common/pipeline.rs
Labels: bug

#1884 Revert "chore: Merge release/1.3.1 into main"
  Cargo.lock
  Cargo.toml
  plugins/zenoh-plugin-rest/Cargo.toml
  plugins/zenoh-plugin-storage-manager/Cargo.toml
  zenoh/Cargo.toml
Labels: internal

#1883 Fix semver checks
  .github/workflows/ci.yml
Labels: release, internal

#1881 Bug/fix batching wait regression
  io/zenoh-transport/src/common/pipeline.rs
  io/zenoh-transport/tests/unicast_transport.rs
Labels: bug, enhancement

#1894 Lowlatency async finalize
  io/zenoh-transport/src/unicast/lowlatency/link.rs
Labels: bug, release

#1851 Maintain keyexpr type in interceptors
  zenoh/src/net/routing/dispatcher/face.rs
  zenoh/src/net/routing/dispatcher/resource.rs
  zenoh/src/net/routing/interceptor/access_control.rs
  zenoh/src/net/routing/interceptor/authorization.rs
  zenoh/src/net/routing/interceptor/downsampling.rs
  zenoh/src/net/routing/interceptor/low_pass.rs
  zenoh/src/net/routing/interceptor/mod.rs
  zenoh/src/net/routing/interceptor/qos_overwrite.rs
  zenoh/src/net/routing/mod.rs
  zenoh/src/tests.rs
Labels: enhancement

#1895 Add low_pass_filter/link_protocols to DEFAULT_CONFIG.json5
  DEFAULT_CONFIG.json5
Labels: internal

#1903 fix: slim down number of profraw files generated
  .github/workflows/ci.yml
Labels: internal

#1865 deny unknown config fields
  commons/zenoh-config/src/lib.rs
Labels: enhancement

#1906 Drop queries when session is closed
  zenoh/src/api/session.rs
Labels: bug, release, internal

#1877 remove useless bound in NetworkMessageIter
  commons/zenoh-codec/src/network/mod.rs
Labels: internal

#1908 [ZEN-548]add zids config parameter to qos_overwrite
  DEFAULT_CONFIG.json5
  commons/zenoh-config/src/lib.rs
  zenoh/src/net/routing/interceptor/qos_overwrite.rs
  zenoh/tests/qos_overwrite.rs
Labels: new feature

#1909 [ZEN-548]allow inserting config list item with its id
  commons/zenoh-config/src/lib.rs
  zenoh/src/api/config.rs
Labels: new feature

#1918 remove todo! from zenoh_backend_traits::config::VolumeConfig::try_from
  plugins/zenoh-backend-traits/src/config.rs
Labels: bug

#1919 fix build warnings for zenoh-plugin-storage-manager
  zenoh/src/net/runtime/adminspace.rs
Labels: bug, internal

#1917 add Queryable::key_expr() method
  zenoh/src/api/builders/queryable.rs
  zenoh/src/api/publisher.rs
  zenoh/src/api/querier.rs
  zenoh/src/api/queryable.rs
Labels: enhancement, api fix

#1922 fix return value of Queryable::key_expr
  zenoh/src/api/queryable.rs
Labels: internal

#1923 Derive `Debug` and `Clone` for `SampleFields`
  zenoh/src/api/sample.rs
Labels: enhancement
