Repository eclipse-zenoh/zenoh, pull requests merged in 2025-06, with the labels that each got.

#1973 fix RecoveryConfig
  zenoh-ext/src/advanced_subscriber.rs
  zenoh-ext/src/subscriber_ext.rs
Labels: enhancement, api fix

#1978 [ZEN-557] do not set zenohid in the config if it is unset, do it in the runtime builder instead
  commons/zenoh-config/src/lib.rs
  io/zenoh-transport/src/manager.rs
  zenoh/src/api/session.rs
  zenoh/src/net/common.rs
  zenoh/src/net/routing/hat/linkstate_peer/mod.rs
  zenoh/src/net/routing/hat/p2p_peer/mod.rs
  zenoh/src/net/routing/hat/router/mod.rs
  zenoh/src/net/routing/interceptor/mod.rs
  zenoh/src/net/runtime/mod.rs
  zenoh/src/net/runtime/orchestrator.rs
  zenoh/src/tests/interceptor_cache.rs
  zenoh/src/tests/link_weights.rs
  zenoh/tests/authentication.rs
  zenoh/tests/liveliness.rs
  zenoh/tests/qos_overwrite.rs
  zenoh/tests/session.rs
  zenohd/src/main.rs
Labels: enhancement, api fix

#1998 Fix bug querying with Target AllComplete on local queryables
  zenoh/src/api/session.rs
Labels: bug

#1999 Make untimestamped replies ordered by arrival
  zenoh/src/api/session.rs
Labels: bug

#1980 [ZEN-557] Extract udp socket source address via PKTINFO
  Cargo.lock
  Cargo.toml
  io/zenoh-links/zenoh-link-udp/Cargo.toml
  io/zenoh-links/zenoh-link-udp/src/lib.rs
  io/zenoh-links/zenoh-link-udp/src/pktinfo/mod.rs
  io/zenoh-links/zenoh-link-udp/src/pktinfo/pktinfo_generic.rs
  io/zenoh-links/zenoh-link-udp/src/pktinfo/pktinfo_unix.rs
  io/zenoh-links/zenoh-link-udp/src/pktinfo/pktinfo_windows.rs
  io/zenoh-links/zenoh-link-udp/src/unicast.rs
Labels: bug

#2003 Fix shm api reexports
  commons/zenoh-shm/src/api/client_storage/mod.rs
  commons/zenoh-shm/src/api/common/types.rs
  commons/zenoh-shm/src/lib.rs
  zenoh/src/lib.rs
Labels: enhancement, release, api sync
