Repository eclipse-zenoh/zenoh, pull requests merged in 2025-05, with the labels that each got.

#1928 Properly set Reply::replier_id
  zenoh/src/api/session.rs
  zenoh/tests/session.rs
Labels: bug

#1931 output edge weights in graph dot format
  zenoh/src/net/protocol/network.rs
Labels: internal

#1930 ci: remove scheduled runs for ci and pre-release
  .github/workflows/ci.yml
  .github/workflows/pre-release.yml
Labels: internal

#1936 Allow providing a full configuration through --cfg argument (#1935)
  zenohd/src/main.rs
Labels: enhancement

#1932 expose routing trees' successors in adminspace
  zenoh/src/net/protocol/network.rs
  zenoh/src/net/routing/hat/client/mod.rs
  zenoh/src/net/routing/hat/mod.rs
  zenoh/src/net/routing/hat/p2p_peer/mod.rs
  zenoh/src/net/routing/hat/router/mod.rs
  zenoh/src/net/runtime/adminspace.rs
Labels: enhancement, internal

#1916 include link stats in adminspace
  io/zenoh-transport/src/common/stats.rs
  io/zenoh-transport/src/unicast/link.rs
  io/zenoh-transport/src/unicast/lowlatency/transport.rs
  io/zenoh-transport/src/unicast/mod.rs
  io/zenoh-transport/src/unicast/transport_unicast_inner.rs
  io/zenoh-transport/src/unicast/universal/link.rs
  io/zenoh-transport/src/unicast/universal/rx.rs
  io/zenoh-transport/src/unicast/universal/transport.rs
  zenoh/src/net/runtime/adminspace.rs
Labels: internal

#1590 Document callback drop on subscriber undeclaration
  zenoh/src/api/subscriber.rs
Labels: documentation, not sure

#1943 enumerate IP interface names for WebSocket link
  io/zenoh-links/zenoh-link-ws/src/unicast.rs
Labels: enhancement, release

#1948 Make sure rustup is updated on the CI (and support 1.87 :) )
  .github/workflows/ci.yml
  commons/zenoh-buffers/src/zbuf.rs
  commons/zenoh-macros/src/lib.rs
  commons/zenoh-sync/src/condition.rs
  commons/zenoh-util/tests/zresult.rs
  io/zenoh-links/zenoh-link-quic/src/unicast.rs
  zenoh/src/api/config.rs
  zenoh/src/net/runtime/orchestrator.rs
Labels: bug, release, internal

#1934 adminspace: Set proper encoding
  zenoh/src/api/admin.rs
Labels: enhancement

#1947 fix std feature propagation for zenoh-buffers
  commons/zenoh-codec/Cargo.toml
  commons/zenoh-protocol/Cargo.toml
Labels: bug, release, internal

#1951 Fix wrong error log in linkstate peers
  zenoh/src/net/routing/hat/linkstate_peer/mod.rs
Labels: bug

#1937 support DSCP link config
  Cargo.lock
  DEFAULT_CONFIG.json5
  io/zenoh-link-commons/Cargo.toml
  io/zenoh-link-commons/src/dscp.rs
  io/zenoh-link-commons/src/lib.rs
  io/zenoh-link-commons/src/tcp.rs
  io/zenoh-links/zenoh-link-quic/src/unicast.rs
  io/zenoh-links/zenoh-link-tcp/src/unicast.rs
  io/zenoh-links/zenoh-link-tcp/src/utils.rs
  io/zenoh-links/zenoh-link-tls/src/utils.rs
  io/zenoh-links/zenoh-link-udp/src/multicast.rs
  io/zenoh-links/zenoh-link-udp/src/unicast.rs
Labels: new feature

#1952 Doc: fix SeqNum and SeqNumGenerator documentation (fix #1949)
  io/zenoh-transport/src/common/seq_num.rs
Labels: documentation

#1956 Bump uhlc to 0.8.1
  Cargo.lock
Labels: internal

#1958 change port for test_link_weights_info_diamond_routers
  zenoh/src/tests/link_weights.rs
Labels: internal
