Repository eclipse-zenoh/zenoh, pull requests merged in 2025-08, with the labels that each got.

#2076 Ignore `three_node_combination_multicast` test
  zenoh/tests/routing.rs
Labels: internal

#2075 Fix multicast transports cleanup on `Session:close`
  io/zenoh-transport/src/manager.rs
  io/zenoh-transport/src/multicast/manager.rs
Labels: bug

#2084 Use inline tables for `package.metadata.deb.assets`
  zenoh/Cargo.toml
  zenohd/Cargo.toml
Labels: bug

#2085 Fix Clippy lints from Rust 1.89
  commons/zenoh-core/src/macros.rs
  examples/examples/z_queryable_shm.rs
  examples/examples/z_sub_shm.rs
  io/zenoh-links/zenoh-link-unixsock_stream/src/lib.rs
  plugins/zenoh-backend-traits/src/config.rs
Labels: internal

#2091 Fix the typos in the configuration.
  DEFAULT_CONFIG.json5
Labels: bug

#2093 fix: consistently use the snake case
  commons/zenoh-config/src/lib.rs
  commons/zenoh-config/src/qos.rs
Labels: bug, breaking-change, internal

#2094 Comment-out logging in cleanup (causes logger panic in atexit())
  commons/zenoh-shm/src/posix_shm/cleanup.rs
  commons/zenoh-shm/src/shm/unix.rs
Labels: bug, release

#2063 Remove ComputedOnMiss
  zenoh/src/net/routing/interceptor/downsampling.rs
  zenoh/src/net/routing/interceptor/mod.rs
Labels: internal

#2068 Box WBatch
  io/zenoh-transport/src/common/pipeline.rs
Labels: internal
