Repository eclipse-zenoh/zenoh, pull requests merged in 2025-03, with the labels that each got.

#1795 make interceptor-rejected queries and liveliness queries return an empty reply instead of timeout
  zenoh/src/net/primitives/demux.rs
  zenoh/src/net/primitives/mux.rs
  zenoh/src/net/routing/dispatcher/face.rs
  zenoh/src/net/routing/dispatcher/interests.rs
  zenoh/src/net/routing/hat/client/interests.rs
  zenoh/src/net/routing/hat/client/token.rs
  zenoh/src/net/routing/hat/p2p_peer/interests.rs
  zenoh/src/net/routing/hat/p2p_peer/token.rs
  zenoh/tests/acl.rs
Labels: bug

#1800 fix: add cargo-machete ignore rule for base64ct
  ci/valgrind-check/Cargo.toml
Labels: internal

#1808 feat: add code coverage report
  .github/workflows/ci.yml
  .gitignore
Labels: internal

#1809 fix: use CODECOV_TOKEN to upload coverage report
  .github/workflows/ci.yml
Labels: internal

#1798 Migrate SHM
  Cargo.lock
  Cargo.toml
  commons/zenoh-shm/Cargo.toml
  commons/zenoh-shm/build.rs
  commons/zenoh-shm/src/api/protocol_implementations/posix/posix_shm_provider_backend.rs
  commons/zenoh-shm/src/api/protocol_implementations/posix/posix_shm_segment.rs
  commons/zenoh-shm/src/lib.rs
  commons/zenoh-shm/src/metadata/segment.rs
  commons/zenoh-shm/src/posix_shm/array.rs
  commons/zenoh-shm/src/posix_shm/cleanup.rs
  commons/zenoh-shm/src/posix_shm/mod.rs
  commons/zenoh-shm/src/posix_shm/segment.rs
  commons/zenoh-shm/src/posix_shm/segment_lock.rs
  commons/zenoh-shm/src/posix_shm/struct_in_shm.rs
  commons/zenoh-shm/src/shm/mod.rs
  commons/zenoh-shm/src/shm/unix.rs
  commons/zenoh-shm/src/shm/windows.rs
  commons/zenoh-shm/tests/common/mod.rs
  commons/zenoh-shm/tests/posix_array.rs
  commons/zenoh-shm/tests/posix_segment.rs
  commons/zenoh-shm/tests/posix_shm_provider.rs
  commons/zenoh-shm/tests/shm.rs
  io/zenoh-transport/src/unicast/establishment/ext/shm.rs
Labels: enhancement, dependencies, release, internal

#1812 fix: add basic codecov.yml
  .codecov.yml
  .config/nextest.toml
  .github/workflows/ci.yml
Labels: internal

#1813 chore: add codecov badge to README
  .codecov.yml
  README.md
Labels: internal

#1792 Namespace prefix support
  DEFAULT_CONFIG.json5
  commons/zenoh-config/src/lib.rs
  commons/zenoh-keyexpr/src/key_expr/borrowed.rs
  commons/zenoh-keyexpr/src/key_expr/mod.rs
  commons/zenoh-keyexpr/src/key_expr/owned.rs
  commons/zenoh-macros/src/lib.rs
  zenoh-ext/src/advanced_cache.rs
  zenoh-ext/src/advanced_publisher.rs
  zenoh-ext/src/advanced_subscriber.rs
  zenoh-ext/src/publication_cache.rs
  zenoh-ext/tests/advanced.rs
  zenoh/src/api/key_expr.rs
  zenoh/src/api/session.rs
  zenoh/src/lib.rs
  zenoh/src/net/primitives/mod.rs
  zenoh/src/net/routing/dispatcher/face.rs
  zenoh/src/net/routing/mod.rs
  zenoh/src/net/routing/namespace.rs
  zenoh/src/net/runtime/adminspace.rs
  zenoh/src/net/tests/tables.rs
  zenoh/tests/namespace.rs
Labels: enhancement

#1816 fix: collect junit reports from each test run
  .github/workflows/ci.yml
Labels: internal

#1797 Add support for query/reply messages to Downsampling
  DEFAULT_CONFIG.json5
  commons/zenoh-config/src/lib.rs
  zenoh/src/net/routing/interceptor/authorization.rs
  zenoh/src/net/routing/interceptor/downsampling.rs
  zenoh/src/net/routing/interceptor/mod.rs
  zenoh/tests/interceptors.rs
Labels: new feature, breaking-change

#1788 Wrap Interceptors with `ArcSwap`
  Cargo.lock
  Cargo.toml
  zenoh/Cargo.toml
  zenoh/src/net/primitives/demux.rs
  zenoh/src/net/primitives/mux.rs
  zenoh/src/net/routing/dispatcher/face.rs
  zenoh/src/net/routing/dispatcher/tables.rs
  zenoh/src/net/routing/router.rs
Labels: internal

#1829 fix: pin url to 2.5.2
  Cargo.toml
Labels: internal

#1830 chore: pin indirect dependencies
  Cargo.toml
Labels: internal

#1831 zenoh_keyexpr should support nostd, std::str:: replaced to core::str::
  commons/zenoh-keyexpr/src/key_expr/borrowed.rs
Labels: internal

#1836 fix: add rust 1.75 CI check
  .github/workflows/ci.yml
Labels: internal

#1838 chore: add check_rust to CI status check
  .github/workflows/ci.yml
Labels: internal

#1803 Bump Rust toolchain to 1.85
  ci/valgrind-check/Cargo.toml
  rust-toolchain.toml
Labels: breaking-change, dependencies

#1839 Replace `to-` with `to_`
  DEFAULT_CONFIG.json5
Labels: internal

#1842 feat: Add TTL connection param to multicast
  io/zenoh-links/zenoh-link-udp/src/lib.rs
  io/zenoh-links/zenoh-link-udp/src/multicast.rs
Labels: enhancement

#1632 Nolocal close
  Cargo.lock
  zenoh/Cargo.toml
  zenoh/build.rs
  zenoh/src/api/builders/close.rs
  zenoh/src/lib.rs
  zenoh/tests/atexit.rs
  zenoh/tests/session.rs
Labels: enhancement, release

#1855 Fix bug with wait_before_close
  io/zenoh-transport/src/common/pipeline.rs
Labels: bug

#1849 Cache invalidation
  Cargo.lock
  commons/zenoh-sync/Cargo.toml
  commons/zenoh-sync/src/cache.rs
  commons/zenoh-sync/src/lib.rs
  zenoh/src/lib.rs
  zenoh/src/net/primitives/demux.rs
  zenoh/src/net/primitives/mux.rs
  zenoh/src/net/routing/dispatcher/face.rs
  zenoh/src/net/routing/dispatcher/resource.rs
  zenoh/src/net/routing/dispatcher/tables.rs
  zenoh/src/net/routing/interceptor/mod.rs
  zenoh/src/net/routing/router.rs
  zenoh/src/tests.rs
Labels: enhancement

#1825 add qos overwrite interceptor
  DEFAULT_CONFIG.json5
  commons/zenoh-config/src/lib.rs
  commons/zenoh-config/src/qos.rs
  zenoh/src/api/publisher.rs
  zenoh/src/net/routing/interceptor/mod.rs
  zenoh/src/net/routing/interceptor/qos_overwrite.rs
  zenoh/tests/qos_overwrite.rs
Labels: new feature

#1821 Cache ACL interceptor results
  zenoh/src/net/routing/interceptor/access_control.rs
  zenoh/src/net/routing/interceptor/authorization.rs
Labels: bug, enhancement

#1858 Fixes #1820
  zenoh/src/api/selector.rs
Labels: documentation

#1856 deserialize frame lazily
  commons/zenoh-codec/src/network/mod.rs
  commons/zenoh-codec/src/transport/frame.rs
  commons/zenoh-protocol/src/transport/frame.rs
  io/zenoh-transport/src/common/pipeline.rs
  io/zenoh-transport/src/multicast/rx.rs
  io/zenoh-transport/src/unicast/universal/rx.rs
Labels: internal

#1862 qos overwriter no longer checks ke of message types that should not be affected
  zenoh/src/net/routing/interceptor/qos_overwrite.rs
Labels: enhancement

#1826 remove recursions from resource tree
  zenoh/src/net/routing/dispatcher/resource.rs
  zenoh/src/net/tests/tables.rs
Labels: internal
