Repository eclipse-zenoh/zenoh, pull requests merged in 2025-02, with the labels that each got.

#1750 docs(storage-manager): improve documentation of Replication
  plugins/zenoh-plugin-storage-manager/src/replication/classification.rs
  plugins/zenoh-plugin-storage-manager/src/replication/configuration.rs
  plugins/zenoh-plugin-storage-manager/src/replication/core.rs
  plugins/zenoh-plugin-storage-manager/src/replication/core/aligner_query.rs
  plugins/zenoh-plugin-storage-manager/src/replication/core/aligner_reply.rs
  plugins/zenoh-plugin-storage-manager/src/replication/digest.rs
  plugins/zenoh-plugin-storage-manager/src/replication/log.rs
  plugins/zenoh-plugin-storage-manager/src/storages_mgt/mod.rs
Labels: documentation

#1749 Reduce TX/RX buffers allocation
  DEFAULT_CONFIG.json5
  commons/zenoh-config/src/lib.rs
  io/zenoh-transport/src/common/pipeline.rs
  io/zenoh-transport/src/manager.rs
  io/zenoh-transport/src/multicast/link.rs
  io/zenoh-transport/src/unicast/lowlatency/link.rs
  io/zenoh-transport/src/unicast/universal/link.rs
Labels: enhancement, internal

#1751 Change default memory allocation policy and size of the queue
  DEFAULT_CONFIG.json5
  commons/zenoh-config/src/defaults.rs
  commons/zenoh-config/src/lib.rs
Labels: enhancement

#1754 fix: fix Resource::get_best_key
  zenoh/src/net/routing/dispatcher/resource.rs
Labels: bug

#1756 SHM lazy init is now configured in config.json
  DEFAULT_CONFIG.json5
  commons/zenoh-config/src/defaults.rs
  commons/zenoh-config/src/lib.rs
  commons/zenoh-shm/src/init.rs
  commons/zenoh-shm/src/lib.rs
  zenoh/src/net/runtime/mod.rs
  zenoh/tests/shm.rs
Labels: new feature, release

#1759 Add downsampling id and update config comment
  DEFAULT_CONFIG.json5
  commons/zenoh-config/src/lib.rs
  zenoh/tests/interceptors.rs
Labels: internal

#1757 fix: fix suffix splitting in `Resource::get_best_key`
  zenoh/src/net/routing/dispatcher/resource.rs
  zenoh/src/net/tests/tables.rs
Labels: internal

#1753 AdvancedSub starts delivering samples as soon as sample_depth samples are received
  zenoh-ext/src/advanced_subscriber.rs
Labels: internal

#1742 feat: avoid duplicate autoconnection attempt
  Cargo.lock
  Cargo.toml
  DEFAULT_CONFIG.json5
  commons/zenoh-config/Cargo.toml
  commons/zenoh-config/src/defaults.rs
  commons/zenoh-config/src/lib.rs
  commons/zenoh-config/src/mode_dependent.rs
  zenoh/src/net/common.rs
  zenoh/src/net/mod.rs
  zenoh/src/net/routing/hat/linkstate_peer/mod.rs
  zenoh/src/net/routing/hat/linkstate_peer/network.rs
  zenoh/src/net/routing/hat/p2p_peer/gossip.rs
  zenoh/src/net/routing/hat/p2p_peer/mod.rs
  zenoh/src/net/routing/hat/router/mod.rs
  zenoh/src/net/routing/hat/router/network.rs
  zenoh/src/net/runtime/orchestrator.rs
Labels: enhancement

#1764 Migrate zenohd to sync API
  Cargo.lock
  zenohd/Cargo.toml
  zenohd/src/main.rs
Labels: enhancement, internal

#1765 Update autoconnect strategy config
  DEFAULT_CONFIG.json5
  commons/zenoh-config/src/mode_dependent.rs
Labels: internal

#1766 Propagate default zenoh features in subcrates and workspace
  Cargo.lock
  Cargo.toml
  examples/Cargo.toml
  plugins/zenoh-backend-example/Cargo.toml
  plugins/zenoh-backend-traits/Cargo.toml
  plugins/zenoh-plugin-rest/Cargo.toml
  plugins/zenoh-plugin-storage-manager/Cargo.toml
  zenoh-ext/Cargo.toml
  zenoh-ext/examples/Cargo.toml
  zenohd/Cargo.toml
Labels: internal

#1770 Expose different congestion control defaults as internal
  commons/zenoh-protocol/Cargo.toml
  commons/zenoh-protocol/src/core/mod.rs
  commons/zenoh-protocol/src/network/mod.rs
  zenoh/Cargo.toml
Labels: internal

#1773 fix: don't cache bin dir
  .github/workflows/ci.yml
Labels: internal

#1571 add empty gravestone values for Sample, Reply, ReplyError, Query and Hello
  commons/zenoh-config/src/wrappers.rs
  zenoh/src/api/query.rs
  zenoh/src/api/queryable.rs
  zenoh/src/api/sample.rs
Labels: internal

#1775 followup to pull/1571: reliability, sourceinfo to unstable
  commons/zenoh-shm/tests/posix_shm_provider.rs
  zenoh/src/api/sample.rs
Labels: internal

#1778 Improve watchdog confirmator warn message
  commons/zenoh-shm/src/watchdog/periodic_task.rs
Labels: internal

#1781 Add policy id to ACL config
  DEFAULT_CONFIG.json5
  commons/zenoh-config/src/lib.rs
  zenoh/src/net/routing/interceptor/authorization.rs
  zenoh/tests/acl.rs
Labels: enhancement

#1785 Enforce downsampling config id unicity
  zenoh/src/net/routing/interceptor/downsampling.rs
  zenoh/tests/interceptors.rs
Labels: bug

#1789 Optimize `FaceState::update_interceptors_caches`
  zenoh/src/net/routing/dispatcher/face.rs
  zenoh/src/net/routing/interceptor/mod.rs
Labels: enhancement

#1786 Do not match keyexprs for local faces
  zenoh/src/net/routing/dispatcher/face.rs
  zenoh/src/net/routing/dispatcher/resource.rs
  zenoh/src/net/routing/hat/linkstate_peer/mod.rs
  zenoh/src/net/routing/hat/linkstate_peer/pubsub.rs
  zenoh/src/net/routing/hat/linkstate_peer/queries.rs
  zenoh/src/net/routing/hat/linkstate_peer/token.rs
  zenoh/src/net/routing/hat/p2p_peer/interests.rs
  zenoh/src/net/routing/hat/p2p_peer/mod.rs
  zenoh/src/net/routing/hat/p2p_peer/pubsub.rs
  zenoh/src/net/routing/hat/p2p_peer/queries.rs
  zenoh/src/net/routing/hat/p2p_peer/token.rs
  zenoh/src/net/routing/hat/router/interests.rs
  zenoh/src/net/routing/hat/router/mod.rs
  zenoh/src/net/routing/hat/router/pubsub.rs
  zenoh/src/net/routing/hat/router/queries.rs
  zenoh/src/net/routing/hat/router/token.rs
  zenoh/src/net/routing/router.rs
Labels: enhancement, internal

#1790 fix: change macos runners to use macos-latest
  .github/workflows/ci.yml
Labels: internal

#1793 Reduce routing resource tree memory consumption
  commons/zenoh-collections/src/lib.rs
  commons/zenoh-collections/src/single_or_box_hashset.rs
  zenoh/src/net/routing/dispatcher/resource.rs
Labels: enhancement

#1791 fix: add step to determine runners
  .github/workflows/ci.yml
Labels: internal

#1799 fix: pin base64ct to 1.6.0 for valgrind-check
  ci/valgrind-check/Cargo.toml
Labels: internal

#1796 Account for link creation in the open timeout
  io/zenoh-transport/src/unicast/manager.rs
Labels: bug
