Repository eclipse-zenoh/zenoh, pull requests merged in 2025-01, with the labels that each got.

#1685 fix: advanced subscriber undeclartion deadlock
  zenoh/src/api/session.rs
Labels: bug, internal

#1682 Add publishers and queriers to admin space
  zenoh/src/net/routing/hat/client/pubsub.rs
  zenoh/src/net/routing/hat/client/queries.rs
  zenoh/src/net/routing/hat/linkstate_peer/pubsub.rs
  zenoh/src/net/routing/hat/linkstate_peer/queries.rs
  zenoh/src/net/routing/hat/mod.rs
  zenoh/src/net/routing/hat/p2p_peer/pubsub.rs
  zenoh/src/net/routing/hat/p2p_peer/queries.rs
  zenoh/src/net/routing/hat/router/pubsub.rs
  zenoh/src/net/routing/hat/router/queries.rs
  zenoh/src/net/runtime/adminspace.rs
Labels: new feature

#1692 Fix #1690
  io/zenoh-transport/src/unicast/manager.rs
Labels: bug

#1678 Add gossip_target configuration option
  DEFAULT_CONFIG.json5
  commons/zenoh-config/src/defaults.rs
  commons/zenoh-config/src/lib.rs
  zenoh/src/net/routing/hat/client/mod.rs
  zenoh/src/net/routing/hat/linkstate_peer/mod.rs
  zenoh/src/net/routing/hat/linkstate_peer/network.rs
  zenoh/src/net/routing/hat/mod.rs
  zenoh/src/net/routing/hat/p2p_peer/gossip.rs
  zenoh/src/net/routing/hat/p2p_peer/mod.rs
  zenoh/src/net/routing/hat/router/mod.rs
  zenoh/src/net/routing/hat/router/network.rs
  zenoh/src/net/routing/router.rs
  zenoh/src/net/runtime/mod.rs
Labels: enhancement, new feature

#1689 fix(storage-manager): incorrectly revive key after deletion
  plugins/zenoh-plugin-storage-manager/src/replication/core/aligner_reply.rs
Labels: bug

#1680 Add expression caching to routing Resource tree
  zenoh/src/net/routing/dispatcher/face.rs
  zenoh/src/net/routing/dispatcher/interests.rs
  zenoh/src/net/routing/dispatcher/pubsub.rs
  zenoh/src/net/routing/dispatcher/queries.rs
  zenoh/src/net/routing/dispatcher/resource.rs
  zenoh/src/net/routing/dispatcher/tables.rs
  zenoh/src/net/routing/dispatcher/token.rs
  zenoh/src/net/routing/hat/client/interests.rs
  zenoh/src/net/routing/hat/client/pubsub.rs
  zenoh/src/net/routing/hat/client/queries.rs
  zenoh/src/net/routing/hat/client/token.rs
  zenoh/src/net/routing/hat/linkstate_peer/pubsub.rs
  zenoh/src/net/routing/hat/linkstate_peer/queries.rs
  zenoh/src/net/routing/hat/linkstate_peer/token.rs
  zenoh/src/net/routing/hat/p2p_peer/interests.rs
  zenoh/src/net/routing/hat/p2p_peer/pubsub.rs
  zenoh/src/net/routing/hat/p2p_peer/queries.rs
  zenoh/src/net/routing/hat/p2p_peer/token.rs
  zenoh/src/net/routing/hat/router/pubsub.rs
  zenoh/src/net/routing/hat/router/queries.rs
  zenoh/src/net/routing/hat/router/token.rs
  zenoh/src/net/routing/mod.rs
  zenoh/src/net/tests/tables.rs
Labels: enhancement

#1696 Fix GarbageCollect policy for corner cases
  commons/zenoh-shm/src/api/provider/shm_provider.rs
Labels: bug, release

#1705 Fix Rust 1.84 clippy lints
  commons/zenoh-keyexpr/src/key_expr/format/mod.rs
  commons/zenoh-keyexpr/src/key_expr/format/parsing.rs
  commons/zenoh-protocol/src/core/endpoint.rs
  commons/zenoh-shm/src/posix_shm/segment_lock.rs
  examples/examples/z_pub_shm.rs
  io/zenoh-links/zenoh-link-unixpipe/src/unix/unicast.rs
  plugins/zenoh-plugin-trait/Cargo.toml
  zenoh/src/api/session.rs
  zenoh/src/net/routing/hat/client/queries.rs
  zenoh/src/net/routing/hat/linkstate_peer/queries.rs
  zenoh/src/net/routing/hat/p2p_peer/queries.rs
  zenoh/src/net/routing/hat/router/queries.rs
Labels: internal

#1704 Scan network interfaces once at startup
  commons/zenoh-util/src/net/mod.rs
Labels: enhancement

#1708 Fix TLS endpoint port propagation in gossip
  io/zenoh-links/zenoh-link-quic/src/unicast.rs
  io/zenoh-links/zenoh-link-quic/src/utils.rs
  io/zenoh-links/zenoh-link-tls/src/unicast.rs
Labels: bug

#1709 removed unnecessary feature from zenoh-plugin-trait to avoid false compatibility errors
  plugins/zenoh-plugin-trait/Cargo.toml
  plugins/zenoh-plugin-trait/src/lib.rs
  plugins/zenoh-plugin-trait/src/vtable.rs
Labels: internal

#1701 Add advanced pub/sub last sample miss detection
  zenoh-ext/examples/examples/z_advanced_pub.rs
  zenoh-ext/examples/examples/z_advanced_sub.rs
  zenoh-ext/src/advanced_publisher.rs
  zenoh-ext/src/advanced_subscriber.rs
  zenoh-ext/src/lib.rs
  zenoh-ext/src/publisher_ext.rs
  zenoh-ext/src/subscriber_ext.rs
  zenoh-ext/tests/advanced.rs
Labels: new feature

#1710 Config: add interests timeout
  DEFAULT_CONFIG.json5
  commons/zenoh-config/src/defaults.rs
  commons/zenoh-config/src/lib.rs
  zenoh/src/net/routing/dispatcher/interests.rs
  zenoh/src/net/routing/dispatcher/tables.rs
  zenoh/src/net/routing/hat/client/interests.rs
  zenoh/src/net/routing/hat/p2p_peer/interests.rs
Labels: enhancement

#1716 ci: rustfmt all files
  .github/workflows/ci.yml
  .github/workflows/pre-release.yml
  .pre-commit-config.yaml
  commons/zenoh-buffers/src/slice.rs
  commons/zenoh-keyexpr/src/keyexpr_tree/impls/hashmap_impl.rs
  commons/zenoh-keyexpr/src/keyexpr_tree/impls/keyed_set_impl.rs
  commons/zenoh-keyexpr/src/keyexpr_tree/impls/vec_set_impl.rs
  commons/zenoh-shm/src/posix_shm/segment.rs
Labels: enhancement, internal

#1712 Use client multicast autoconnect config
  DEFAULT_CONFIG.json5
  commons/zenoh-config/src/defaults.rs
  zenoh/src/net/runtime/orchestrator.rs
Labels: bug

#1715 Test ports
  io/zenoh-transport/tests/unicast_authenticator.rs
  zenoh-ext/tests/advanced.rs
  zenoh-ext/tests/liveliness.rs
  zenoh/tests/liveliness.rs
Labels: bug, release, internal

#1718 fix: add missing exports of advanced publication builders
  zenoh-ext/src/lib.rs
Labels: enhancement, api fix

#1719 fix: fix pre-commit command for fish shell
  .pre-commit-config.yaml
Labels: internal

#1717 Update routes pre computation strategy to pre compute less routes
  zenoh/src/net/routing/dispatcher/pubsub.rs
  zenoh/src/net/routing/dispatcher/queries.rs
  zenoh/src/net/routing/dispatcher/resource.rs
  zenoh/src/net/routing/hat/client/mod.rs
  zenoh/src/net/routing/hat/client/pubsub.rs
  zenoh/src/net/routing/hat/client/queries.rs
  zenoh/src/net/routing/hat/linkstate_peer/mod.rs
  zenoh/src/net/routing/hat/linkstate_peer/pubsub.rs
  zenoh/src/net/routing/hat/linkstate_peer/queries.rs
  zenoh/src/net/routing/hat/mod.rs
  zenoh/src/net/routing/hat/p2p_peer/mod.rs
  zenoh/src/net/routing/hat/p2p_peer/pubsub.rs
  zenoh/src/net/routing/hat/p2p_peer/queries.rs
  zenoh/src/net/routing/hat/router/mod.rs
  zenoh/src/net/routing/hat/router/pubsub.rs
  zenoh/src/net/routing/hat/router/queries.rs
Labels: enhancement

#1713 refactor: lazily compute the push body
  zenoh/src/api/session.rs
  zenoh/src/net/routing/dispatcher/face.rs
  zenoh/src/net/routing/dispatcher/pubsub.rs
  zenoh/src/net/tests/tables.rs
Labels: internal

#1686 [ Tracing] Add instrumentation support
  Cargo.lock
  commons/zenoh-core/Cargo.toml
  commons/zenoh-runtime/Cargo.toml
  commons/zenoh-runtime/src/lib.rs
  commons/zenoh-task/Cargo.toml
  commons/zenoh-task/src/lib.rs
  zenoh/Cargo.toml
Labels: internal

#1723 refactor: use foldhash in critical path
  Cargo.lock
  Cargo.toml
  zenoh/Cargo.toml
  zenoh/src/api/session.rs
  zenoh/src/net/routing/dispatcher/face.rs
  zenoh/src/net/routing/dispatcher/resource.rs
Labels: internal

#1720 Add getrandom crate feature=js for KeyExpr
  Cargo.lock
  Cargo.toml
  commons/zenoh-keyexpr/Cargo.toml
Labels: internal

#1722 Update DEFAULT_CONFIG.json5
  DEFAULT_CONFIG.json5
Labels: internal

#1653 Derive Deserialize for enums used in remote-api-plugin
  commons/zenoh-protocol/src/core/mod.rs
  commons/zenoh-protocol/src/network/request.rs
  commons/zenoh-protocol/src/zenoh/query.rs
  zenoh/src/api/publisher.rs
  zenoh/src/api/query.rs
  zenoh/src/api/sample.rs
Labels: enhancement

#1725 Revert "refactor: use foldhash in critical path"
  Cargo.lock
  Cargo.toml
  zenoh/Cargo.toml
  zenoh/src/api/session.rs
  zenoh/src/net/routing/dispatcher/face.rs
  zenoh/src/net/routing/dispatcher/resource.rs
Labels: internal

#1728 Merge Release/1.1.1 into main
  Cargo.lock
  Cargo.toml
  plugins/zenoh-plugin-rest/Cargo.toml
  plugins/zenoh-plugin-storage-manager/Cargo.toml
  zenoh/Cargo.toml
Labels: internal

#1729 fix: update changelog to exclude internal
  .github/release.yml
Labels: internal

#1731 Extend priority range syntax
  commons/zenoh-protocol/src/core/mod.rs
Labels: enhancement

#1736 refactor: avoid temporary allocation in `Resource::get_best_key`
  zenoh/src/net/routing/dispatcher/resource.rs
Labels: internal

#1735 refactor: compute routes on demand
  zenoh/src/net/routing/dispatcher/face.rs
  zenoh/src/net/routing/dispatcher/pubsub.rs
  zenoh/src/net/routing/dispatcher/queries.rs
  zenoh/src/net/routing/dispatcher/resource.rs
  zenoh/src/net/routing/dispatcher/tables.rs
  zenoh/src/net/routing/hat/client/mod.rs
  zenoh/src/net/routing/hat/client/pubsub.rs
  zenoh/src/net/routing/hat/client/queries.rs
  zenoh/src/net/routing/hat/linkstate_peer/mod.rs
  zenoh/src/net/routing/hat/linkstate_peer/pubsub.rs
  zenoh/src/net/routing/hat/linkstate_peer/queries.rs
  zenoh/src/net/routing/hat/mod.rs
  zenoh/src/net/routing/hat/p2p_peer/mod.rs
  zenoh/src/net/routing/hat/p2p_peer/pubsub.rs
  zenoh/src/net/routing/hat/p2p_peer/queries.rs
  zenoh/src/net/routing/hat/router/mod.rs
  zenoh/src/net/routing/hat/router/pubsub.rs
  zenoh/src/net/routing/hat/router/queries.rs
  zenoh/src/net/routing/router.rs
Labels: internal

#1740 fix: fix pipeline congestion shortcut synchronization
  io/zenoh-transport/src/common/pipeline.rs
Labels: bug

#1743 fix: handle linkstate decoding error
  zenoh/src/net/routing/hat/linkstate_peer/mod.rs
  zenoh/src/net/routing/hat/p2p_peer/mod.rs
  zenoh/src/net/routing/hat/router/mod.rs
Labels: bug

#1732 Test ports again
  zenoh-ext/tests/advanced.rs
Labels: bug, internal

#1741 refactor: use a version number for routes computation
  zenoh/src/net/routing/dispatcher/face.rs
  zenoh/src/net/routing/dispatcher/pubsub.rs
  zenoh/src/net/routing/dispatcher/queries.rs
  zenoh/src/net/routing/dispatcher/resource.rs
  zenoh/src/net/routing/dispatcher/tables.rs
  zenoh/src/net/routing/hat/client/mod.rs
  zenoh/src/net/routing/hat/client/pubsub.rs
  zenoh/src/net/routing/hat/client/queries.rs
  zenoh/src/net/routing/hat/linkstate_peer/mod.rs
  zenoh/src/net/routing/hat/linkstate_peer/pubsub.rs
  zenoh/src/net/routing/hat/linkstate_peer/queries.rs
  zenoh/src/net/routing/hat/p2p_peer/mod.rs
  zenoh/src/net/routing/hat/p2p_peer/pubsub.rs
  zenoh/src/net/routing/hat/p2p_peer/queries.rs
  zenoh/src/net/routing/hat/router/mod.rs
  zenoh/src/net/routing/hat/router/pubsub.rs
  zenoh/src/net/routing/hat/router/queries.rs
  zenoh/src/net/routing/router.rs
Labels: internal

#1744 Remove unnecessary mutex lock and drop in pipeline serialization
  io/zenoh-transport/src/common/pipeline.rs
Labels: internal

#1606 fix: precise query id rollover semantic
  zenoh/src/net/routing/dispatcher/queries.rs
Labels: enhancement
