Repository eclipse-zenoh/zenoh, pull requests merged in 2025-09, with the labels that each got.

#1888 cache pipeline selection
  Cargo.lock
  io/zenoh-transport/Cargo.toml
  io/zenoh-transport/src/unicast/link.rs
  io/zenoh-transport/src/unicast/universal/link.rs
  io/zenoh-transport/src/unicast/universal/transport.rs
  io/zenoh-transport/src/unicast/universal/tx.rs
Labels: internal

#2034 SHM typed API
  Cargo.lock
  commons/zenoh-macros/src/zenoh_runtime_derive.rs
  commons/zenoh-shm/src/api/buffer/mod.rs
  commons/zenoh-shm/src/api/buffer/traits.rs
  commons/zenoh-shm/src/api/buffer/typed.rs
  commons/zenoh-shm/src/api/buffer/zshm.rs
  commons/zenoh-shm/src/api/buffer/zshmmut.rs
  commons/zenoh-shm/src/api/protocol_implementations/posix/posix_shm_provider_backend.rs
  commons/zenoh-shm/src/api/provider/memory_layout.rs
  commons/zenoh-shm/src/api/provider/mod.rs
  commons/zenoh-shm/src/api/provider/shm_provider.rs
  commons/zenoh-shm/src/api/provider/shm_provider_backend.rs
  commons/zenoh-shm/src/api/provider/types.rs
  commons/zenoh-shm/src/lib.rs
  commons/zenoh-shm/tests/posix_shm_provider.rs
  commons/zenoh-shm/tests/shm_buffer.rs
  examples/examples/z_alloc_shm.rs
  examples/examples/z_posix_shm_provider.rs
  io/zenoh-transport/tests/unicast_shm.rs
  zenoh/src/api/bytes.rs
  zenoh/src/lib.rs
  zenoh/tests/bytes.rs
  zenoh/tests/shm.rs
Labels: enhancement, new feature, breaking-change, rust

#2115 Add put and delete downsampling message types
  DEFAULT_CONFIG.json5
  commons/zenoh-config/src/lib.rs
  zenoh/src/net/routing/interceptor/downsampling.rs
  zenoh/tests/interceptors.rs
Labels: enhancement, api fix

#2103 ci: run tests with sudo on macos-latest
  .github/workflows/ci.yml
Labels: internal

#2109 refactor RoutingExpr to avoid useless allocation
  zenoh/src/net/routing/dispatcher/pubsub.rs
  zenoh/src/net/routing/dispatcher/queries.rs
  zenoh/src/net/routing/dispatcher/resource.rs
  zenoh/src/net/routing/dispatcher/tables.rs
  zenoh/src/net/routing/hat/client/mod.rs
  zenoh/src/net/routing/hat/client/pubsub.rs
  zenoh/src/net/routing/hat/client/queries.rs
  zenoh/src/net/routing/hat/linkstate_peer/mod.rs
  zenoh/src/net/routing/hat/linkstate_peer/pubsub.rs
  zenoh/src/net/routing/hat/linkstate_peer/queries.rs
  zenoh/src/net/routing/hat/mod.rs
  zenoh/src/net/routing/hat/p2p_peer/mod.rs
  zenoh/src/net/routing/hat/p2p_peer/pubsub.rs
  zenoh/src/net/routing/hat/p2p_peer/queries.rs
  zenoh/src/net/routing/hat/router/mod.rs
  zenoh/src/net/routing/hat/router/pubsub.rs
  zenoh/src/net/routing/hat/router/queries.rs
Labels: question, internal

#2127 use matches to compute routes
  Cargo.lock
  commons/zenoh-collections/src/int_hash_map.rs
  zenoh/src/net/routing/dispatcher/face.rs
  zenoh/src/net/routing/dispatcher/resource.rs
  zenoh/src/net/routing/hat/client/pubsub.rs
  zenoh/src/net/routing/hat/client/queries.rs
  zenoh/src/net/routing/hat/p2p_peer/pubsub.rs
  zenoh/src/net/routing/hat/p2p_peer/queries.rs
Labels: internal

#2117 Shm allocators
  Cargo.lock
  Cargo.toml
  commons/zenoh-shm/Cargo.toml
  commons/zenoh-shm/src/api/protocol_implementations/posix/mod.rs
  commons/zenoh-shm/src/api/protocol_implementations/posix/posix_shm_provider_backend.rs
  commons/zenoh-shm/src/api/protocol_implementations/posix/posix_shm_provider_backend_binary_heap.rs
  commons/zenoh-shm/src/api/protocol_implementations/posix/posix_shm_provider_backend_buddy.rs
  commons/zenoh-shm/src/api/protocol_implementations/posix/posix_shm_provider_backend_talc.rs
  commons/zenoh-shm/tests/posix_shm_provider.rs
  io/zenoh-transport/tests/unicast_shm.rs
  zenoh/src/lib.rs
  zenoh/tests/shm.rs
Labels: enhancement

#2132 implement Error for `ZLayoutError`
  commons/zenoh-shm/src/api/provider/types.rs
Labels: enhancement

#2134 add missing error implementations for shared memory
  commons/zenoh-shm/src/api/provider/types.rs
Labels: enhancement

#2101 fix: narrow SessionState lock guard scope when MatchingListener drop
  zenoh/src/api/session.rs
Labels: bug

#2150 Update the crate dependencies without any API changes.
  Cargo.lock
  Cargo.toml
Labels: internal

#2013 use dynamic runtime in plugins
  Cargo.lock
  commons/zenoh-config/src/lib.rs
  commons/zenoh-util/Cargo.toml
  commons/zenoh-util/src/ffi/mod.rs
  plugins/zenoh-backend-example/Cargo.toml
  plugins/zenoh-backend-example/src/lib.rs
  plugins/zenoh-backend-traits/src/config.rs
  plugins/zenoh-backend-traits/src/lib.rs
  plugins/zenoh-plugin-example/src/lib.rs
  plugins/zenoh-plugin-rest/src/lib.rs
  plugins/zenoh-plugin-storage-manager/Cargo.toml
  plugins/zenoh-plugin-storage-manager/src/lib.rs
  plugins/zenoh-plugin-storage-manager/src/memory_backend/mod.rs
  plugins/zenoh-plugin-storage-manager/src/replication/core.rs
  plugins/zenoh-plugin-storage-manager/src/storages_mgt/service.rs
  plugins/zenoh-plugin-storage-manager/tests/operations.rs
  plugins/zenoh-plugin-storage-manager/tests/wildcard.rs
  plugins/zenoh-plugin-trait/Cargo.toml
  plugins/zenoh-plugin-trait/src/compatibility.rs
  plugins/zenoh-plugin-trait/src/lib.rs
  plugins/zenoh-plugin-trait/src/manager/dynamic_plugin.rs
  plugins/zenoh-plugin-trait/src/plugin.rs
  plugins/zenoh-plugin-trait/src/vtable.rs
  zenoh/src/api/admin.rs
  zenoh/src/api/builders/info.rs
  zenoh/src/api/builders/session.rs
  zenoh/src/api/info.rs
  zenoh/src/api/liveliness.rs
  zenoh/src/api/loader.rs
  zenoh/src/api/plugins.rs
  zenoh/src/api/session.rs
  zenoh/src/lib.rs
  zenoh/src/net/primitives/mod.rs
  zenoh/src/net/runtime/adminspace.rs
  zenoh/src/net/runtime/mod.rs
  zenoh/src/tests/interceptor_cache.rs
  zenoh/src/tests/link_weights.rs
  zenoh/tests/session.rs
Labels: bug, enhancement

#2156 fix liveliness query and liveliness subscriber id overlapping
  zenoh/src/api/session.rs
Labels: bug

#2152 Fix bug leading to reliable messages drop when sent along best effort messages
  commons/zenoh-buffers/src/bbuf.rs
  commons/zenoh-buffers/src/lib.rs
  commons/zenoh-buffers/src/slice.rs
  commons/zenoh-buffers/src/vec.rs
  commons/zenoh-buffers/src/zbuf.rs
  commons/zenoh-buffers/src/zslice.rs
  commons/zenoh-buffers/tests/readwrite.rs
  commons/zenoh-codec/src/network/mod.rs
  commons/zenoh-codec/src/transport/batch.rs
  commons/zenoh-codec/src/transport/frame.rs
  commons/zenoh-codec/src/transport/mod.rs
  commons/zenoh-protocol/src/transport/frame.rs
  io/zenoh-transport/src/common/batch.rs
  io/zenoh-transport/src/common/pipeline.rs
  io/zenoh-transport/src/multicast/rx.rs
  io/zenoh-transport/src/unicast/universal/rx.rs
Labels: bug

#2157 chore: pin rocksdb to 0.23.0
  commons/zenoh-pinned-deps-1-75/Cargo.toml
Labels: internal

#2160 Respect liveliness subscriber history when processing token declarations
  zenoh/src/api/admin.rs
  zenoh/src/api/session.rs
  zenoh/src/api/subscriber.rs
  zenoh/tests/liveliness.rs
Labels: bug

#2174 Improve scalability
  zenoh/src/net/routing/hat/client/interests.rs
  zenoh/src/net/routing/hat/client/queries.rs
  zenoh/src/net/routing/hat/client/token.rs
  zenoh/src/net/routing/hat/linkstate_peer/interests.rs
  zenoh/src/net/routing/hat/linkstate_peer/queries.rs
  zenoh/src/net/routing/hat/linkstate_peer/token.rs
  zenoh/src/net/routing/hat/p2p_peer/interests.rs
  zenoh/src/net/routing/hat/p2p_peer/queries.rs
  zenoh/src/net/routing/hat/p2p_peer/token.rs
  zenoh/src/net/routing/hat/router/interests.rs
  zenoh/src/net/routing/hat/router/queries.rs
  zenoh/src/net/routing/hat/router/token.rs
Labels: enhancement
