Repository eclipse-zenoh/zenoh, pull requests merged in 2025-07, with the labels that each got.

#1988 avoid a useless payload clone in resolve_put
  zenoh/src/api/session.rs
Labels: internal

#2024 Polish shm (for zshm examle)
  commons/zenoh-shm/src/api/buffer/traits.rs
  commons/zenoh-shm/src/api/provider/shm_provider.rs
  zenoh/src/lib.rs
Labels: documentation, release, api fix

#1991 Accept a boolean value for the `complete` field of storage_manager config
  DEFAULT_CONFIG.json5
  plugins/zenoh-backend-traits/src/config.rs
Labels: bug

#1993 Update README how to avoid an out-of-memory error
  README.md
Labels: documentation

#2014 add CongestionControl::BlockFirst
  commons/zenoh-config/src/qos.rs
  commons/zenoh-protocol/Cargo.toml
  commons/zenoh-protocol/src/core/mod.rs
  commons/zenoh-protocol/src/network/mod.rs
  io/zenoh-transport/src/unicast/universal/transport.rs
  io/zenoh-transport/src/unicast/universal/tx.rs
  zenoh/Cargo.toml
Labels: new feature

#2006 Improve error message when opening an empty file
  commons/zenoh-config/src/lib.rs
  zenohd/src/main.rs
Labels: enhancement

#2035 Avoid key expression checks in local query handling
  zenoh/src/api/queryable.rs
  zenoh/src/api/session.rs
  zenoh/tests/attachments.rs
Labels: enhancement

#2051 stabilize querier and matching status/listener
  examples/Cargo.toml
  examples/examples/z_pub.rs
  examples/examples/z_querier.rs
  zenoh/src/api/builders/matching_listener.rs
  zenoh/src/api/builders/mod.rs
  zenoh/src/api/builders/publisher.rs
  zenoh/src/api/builders/querier.rs
  zenoh/src/api/builders/queryable.rs
  zenoh/src/api/builders/subscriber.rs
  zenoh/src/api/matching.rs
  zenoh/src/api/mod.rs
  zenoh/src/api/publisher.rs
  zenoh/src/api/querier.rs
  zenoh/src/api/sample.rs
  zenoh/src/api/session.rs
  zenoh/src/lib.rs
  zenoh/src/net/routing/dispatcher/pubsub.rs
  zenoh/src/net/routing/dispatcher/queries.rs
  zenoh/src/net/routing/hat/client/pubsub.rs
  zenoh/src/net/routing/hat/client/queries.rs
  zenoh/src/net/routing/hat/linkstate_peer/pubsub.rs
  zenoh/src/net/routing/hat/linkstate_peer/queries.rs
  zenoh/src/net/routing/hat/mod.rs
  zenoh/src/net/routing/hat/p2p_peer/pubsub.rs
  zenoh/src/net/routing/hat/p2p_peer/queries.rs
  zenoh/src/net/routing/hat/router/pubsub.rs
  zenoh/src/net/routing/hat/router/queries.rs
  zenoh/tests/matching.rs
  zenoh/tests/namespace.rs
  zenoh/tests/session.rs
Labels: enhancement

#2054 clean tests
  commons/zenoh-codec/benches/codec.rs
  commons/zenoh-protocol/src/network/mod.rs
  commons/zenoh-protocol/src/network/push.rs
  commons/zenoh-protocol/src/zenoh/del.rs
  commons/zenoh-protocol/src/zenoh/put.rs
  io/zenoh-transport/src/common/batch.rs
  io/zenoh-transport/src/common/pipeline.rs
  io/zenoh-transport/tests/multicast_compression.rs
  io/zenoh-transport/tests/multicast_transport.rs
  io/zenoh-transport/tests/unicast_compression.rs
  io/zenoh-transport/tests/unicast_concurrent.rs
  io/zenoh-transport/tests/unicast_fragmentation.rs
  io/zenoh-transport/tests/unicast_intermittent.rs
  io/zenoh-transport/tests/unicast_priorities.rs
  io/zenoh-transport/tests/unicast_shm.rs
  io/zenoh-transport/tests/unicast_simultaneous.rs
  io/zenoh-transport/tests/unicast_transport.rs
  zenoh/Cargo.toml
  zenoh/src/net/tests/tables.rs
Labels: internal

#2059 Add matching listener handler getters
  zenoh/src/api/matching.rs
Labels: enhancement, api fix

#2058 fix IntHashMap::contains_key
  commons/zenoh-collections/src/int_hash_map.rs
Labels: bug

#2053 Improve interceptors performances
  zenoh/src/net/primitives/demux.rs
  zenoh/src/net/primitives/mux.rs
  zenoh/src/net/routing/interceptor/access_control.rs
  zenoh/src/net/routing/interceptor/downsampling.rs
  zenoh/src/net/routing/interceptor/low_pass.rs
  zenoh/src/net/routing/interceptor/mod.rs
  zenoh/src/net/routing/interceptor/qos_overwrite.rs
  zenoh/src/net/routing/mod.rs
  zenoh/src/tests/interceptor_cache.rs
  zenoh/src/tests/link_weights.rs
Labels: enhancement

#2015 Add ZID subject property to ACL
  DEFAULT_CONFIG.json5
  commons/zenoh-config/src/lib.rs
  io/zenoh-transport/src/unicast/authentication.rs
  io/zenoh-transport/src/unicast/lowlatency/transport.rs
  io/zenoh-transport/src/unicast/universal/transport.rs
  zenoh/src/net/routing/interceptor/access_control.rs
  zenoh/src/net/routing/interceptor/authorization.rs
  zenoh/tests/authentication.rs
Labels: new feature

#2012 Fix `Session::close` timeout while client attempts to reconnect
  zenoh/src/net/runtime/orchestrator.rs
Labels: bug

#2025 Refactor `KeyExpr::try_from<&str>` and add some tests
  Cargo.lock
  Cargo.toml
  commons/zenoh-keyexpr/Cargo.toml
  commons/zenoh-keyexpr/src/key_expr/borrowed.rs
  commons/zenoh-keyexpr/src/key_expr/mod.rs
Labels: enhancement

#2061 Report proper whatami for adminspace entities
  zenoh/src/net/routing/hat/linkstate_peer/pubsub.rs
  zenoh/src/net/routing/hat/linkstate_peer/queries.rs
  zenoh/src/net/routing/hat/p2p_peer/pubsub.rs
  zenoh/src/net/routing/hat/p2p_peer/queries.rs
  zenoh/src/net/routing/hat/router/pubsub.rs
  zenoh/src/net/routing/hat/router/queries.rs
Labels: bug

#2060 feat: make CongestionControl and Priority hashable
  commons/zenoh-protocol/src/core/mod.rs
  zenoh/src/api/publisher.rs
Labels: enhancement

#2062 avoid copying shm buffer when sending it on network
  commons/zenoh-codec/src/core/zbuf.rs
  io/zenoh-transport/src/shm.rs
Labels: internal

#2064 chore: simplify the shm conversion in the example
  examples/examples/z_sub_shm.rs
Labels: internal

#2057 Format TOML files using Taplo
  .config/nextest.toml
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  .taplo.toml
  Cargo.toml
  Cross.toml
  _typos.toml
  ci/nostd-check/Cargo.toml
  ci/valgrind-check/Cargo.toml
  clippy.toml
  commons/zenoh-buffers/Cargo.toml
  commons/zenoh-codec/Cargo.toml
  commons/zenoh-collections/Cargo.toml
  commons/zenoh-config/Cargo.toml
  commons/zenoh-core/Cargo.toml
  commons/zenoh-crypto/Cargo.toml
  commons/zenoh-keyexpr/Cargo.toml
  commons/zenoh-macros/Cargo.toml
  commons/zenoh-protocol/Cargo.toml
  commons/zenoh-result/Cargo.toml
  commons/zenoh-runtime/Cargo.toml
  commons/zenoh-shm/Cargo.toml
  commons/zenoh-sync/Cargo.toml
  commons/zenoh-task/Cargo.toml
  commons/zenoh-util/Cargo.toml
  deny.toml
  examples/Cargo.toml
  io/zenoh-link-commons/Cargo.toml
  io/zenoh-link/Cargo.toml
  io/zenoh-links/zenoh-link-quic/Cargo.toml
  io/zenoh-links/zenoh-link-quic_datagram/Cargo.toml
  io/zenoh-links/zenoh-link-serial/Cargo.toml
  io/zenoh-links/zenoh-link-tcp/Cargo.toml
  io/zenoh-links/zenoh-link-tls/Cargo.toml
  io/zenoh-links/zenoh-link-udp/Cargo.toml
  io/zenoh-links/zenoh-link-unixpipe/Cargo.toml
  io/zenoh-links/zenoh-link-unixsock_stream/Cargo.toml
  io/zenoh-links/zenoh-link-vsock/Cargo.toml
  io/zenoh-links/zenoh-link-ws/Cargo.toml
  io/zenoh-transport/Cargo.toml
  plugins/zenoh-backend-example/Cargo.toml
  plugins/zenoh-backend-traits/Cargo.toml
  plugins/zenoh-plugin-example/Cargo.toml
  plugins/zenoh-plugin-rest/Cargo.toml
  plugins/zenoh-plugin-storage-manager/Cargo.toml
  plugins/zenoh-plugin-trait/Cargo.toml
  rustfmt.toml
  zenoh-ext/Cargo.toml
  zenoh-ext/examples/Cargo.toml
  zenoh/Cargo.toml
  zenohd/Cargo.toml
Labels: internal
